### ISSUE TITLE
Amélioration : remise zone à blanc après restore V3.68.1 (1389baf branche V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#101]
Après une restauration au clic de OK restore correct, remettre à blanc la zone 'emplacement de la sauvegarde'.
Pourquoi ? Si l'on est dérangé et que l'on a fait OK sur le restore correct, on ne sait plus si on a cliqué sur 'Restaurer' ...
c'est sur dans ce cas, on refait le restaure par sécurité, mais si la zone était à blanc on ne se poserait pas la question !

**Comment by damscot** [comment]
Je préferais qu'après la sauvegarde ou la restoration quand c'est OK la
fenetre se fermet après le message de confirmation...
pareil il s'agit d'une "Amélioration" rajoute ce champ dans le titre du
ticket.
