### ISSUE TITLE
Amélioration : pouvoir imprimer les produits à stock négatif V3.68.1 (1389baf V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#103]
Tout est dans le texte !

**Comment by Laurux** [comment]
Stock ==> Impression produits à commander

**Comment by damscot** [comment]
attention ceci ne fonctionne que vous avez saisis un nombre min/max dans la
gestion de stock de cet article...
sinon le calcul du "reassor" n'est pas fait.

2018-03-17 14:59 GMT+01:00 Laurux <notifications@github.com>:

**Comment by damscot** [comment]
une fois de plus paty ne pose un ticket que lorsque le bug est confirmé sur
le forum,
sinon git va etre saturé de ticket de question alors que ce n'est pas la
but de cet environement.

2018-03-18 11:04 GMT+01:00 Damien Cottier <damscot@gmail.com>:
