### ISSUE TITLE
Unable to save settings: Settings.Save.200 Null object.

### ISSUE THREAD

**Issue by yohanboniface** [Laurux/Laurux#109]
Bonjour,

Je cherche à tester Laurux pour un ami.
J'ai installé Gambas3 (sur Archlinux), j'ai téléchargé le binaire depuis https://www.laurux.fr/drupal/telechargement, je l'ai décompressé et quand je l'exécute `Laurux`, j'ai cette fenêtre, qui est plutôt absconse pour moi:

![screenshot-20180402151312-504x408](https://user-images.githubusercontent.com/146023/38197566-225290ec-3689-11e8-8866-3cd4ea2310b2.png)

Dans la console:
```
Settings.Save.204: Unable to save settings: Settings.Save.200 Null object
Settings.Save.204 Start.Main.91 
```

Une idée de ce qui cloche?

Merci! :)

PS: l'[install.md](https://github.com/Laurux/Laurux/blob/master/INSTALL.md) est un cul-de-sac en l'état

**Comment by damscot** [comment]
Quelle version de package gambas est disponible sur ArchLinux ?
Pouvez-vous vérifier que le répertoire ~/.config/gambas3/ existe et que les
droits vous permettent d'y accèder.

Il faut aujourd'hui gambas 3.10 pour Laurux.

Intall.md:
pour l'install https://www.laurux.fr/docs/Ecrans/Install.html (c'est vieux
et en parti obsolete)
c'est tout ce que l'on a comme aide pour l'instant... le bénévolat ce fait
rare et
c'est tout ce que l'on peut faire pour l'instant.

**Comment by yohanboniface** [comment]
> Quelle version de package gambas est disponible sur ArchLinux ? 

3.10.0

> Pouvez-vous vérifier que le répertoire ~/.config/gambas3/ existe 

C'était pas le cas, en le créant ça va tout de suite mieux :)


Merci!
