### ISSUE TITLE
nouvel article / code famille

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#11]
=== Laurux 3.67.11 ===

A la création d'un nouvel article : quand on tape le code famille (plutôt que le chercher dans la liste déroulante), les paramètres de la famille ne sont pas pris en compte.

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:47, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> A la création d'un nouvel article : quand on tape le code famille 
> (plutôt que le chercher dans la liste déroulante), les paramètres de la 
> famille ne sont pas pris en compte.

Il y a le problème parce que l'utilisatrice ne valide pas. Elle passe à 
la zone suivante avec la souris.

NB : c'est bien plus rapide de travailler au clavier. Ca évite de 
prendre la souris à chaque fois.



-- 
Jacky Tripoteau

**Comment by brunoc68** [comment]
J'ai tenté avec TAB sans la souris : le problème est bien là.

**Comment by damscot** [comment]
Jacky tu peux verifier que le pb n'est pas la sur master et le corrigé le
cas echeant.
pour moi le workaround d'utiliser tab est acceptable a court terme

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:47, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> A la création d'un nouvel article : quand on tape le code famille 
> (plutôt que le chercher dans la liste déroulante), les paramètres de la 
> famille ne sont pas pris en compte.

Ce problème n'existe pas sur la 3.68.


-- 
Jacky Tripoteau
