### ISSUE TITLE
Saisie de trésorerie

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#119]
Forum : https://www.laurux.fr/drupal/node/245
Lorsque l'on rappelle des écritures non validées en trésorerie les comptes de la classe 6 et 7 perdent leurs 0 en a la fin.  Par contre il serait quand même bien de se renseigner sur la bonne pratique avant de faire des modifs.

**Comment by damscot** [comment]
aucun pb visible sur master avec le compte 6 avec 6 ou 7 caractère je pense que ce pb est un artefact de la configuration de compte de Sylvie.
sans base de donnée, impossible a reproduire
