### ISSUE TITLE
Passage commande->facture avec un matériel

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#12]
=== Laurux 3.67.11 ===

Quand on saisie une commande de matériel puis qu'on la convertit en facture, on doit rappeler le matériel pour saisir le numéro de série ; mais on ne voit pas le numéro de série sur la facture.

Attention : le problème ne se produit pas quand on saisit directement la facture avec le matériel : le numéro de série apparaît bien sur la facture.

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:50, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> Quand on saisie une commande de matériel puis qu'on la convertit en 
> facture, on doit rappeler le matériel pour saisir le numéro de série ; 
> mais on ne voit pas le numéro de série sur la facture.
> 
> Attention : le problème ne se produit pas quand on saisit directement la 
> facture avec le matériel : le numéro de série apparaît bien sur la facture.

Je vais faire des tests pour voir.

-- 
Jacky Tripoteau

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:50, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> Quand on saisie une commande de matériel puis qu'on la convertit en 
> facture, on doit rappeler le matériel pour saisir le numéro de série ; 
> mais on ne voit pas le numéro de série sur la facture.
> 
> Attention : le problème ne se produit pas quand on saisit directement la 
> facture avec le matériel : le numéro de série apparaît bien sur la facture.

Bruno, dis-moi si j'ai bien compris.
Le numéro de série apparaît sur le bl  mais pas à l'impression ?



-- 
Jacky Tripoteau

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:50, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> Quand on saisie une commande de matériel puis qu'on la convertit en 
> facture, on doit rappeler le matériel pour saisir le numéro de série ; 
> mais on ne voit pas le numéro de série sur la facture.
> 
> Attention : le problème ne se produit pas quand on saisit directement la 
> facture avec le matériel : le numéro de série apparaît bien sur la facture.

OK, vu.
1- On passe une commande d'un matériel, il n'y a pas de saisie de numéro 
de saisie.
2- On transforme la commande en BL ou facture, on doit saisir le numéro 
de saisie. La fiche du matériel passe en vendu avec les coordonnées du 
client.
3- Si on retransforme le BL ou la facture en commande, le matériel reste 
en vendu. Il est alors normal qu'il n'apparaissent plus en BL.
Il faut alors aller dans la fiche du matériel pour le décocher 
manuellement.
Je pense que ce fonctionnement restera comme ça car il n'y a pas de 
raison de passer un BL ou une facture en commande.

Cependant en suppression d'un matériel dans un BL ou Facture la fiche du 
matériel n'était pas mise à jour. J'ai apporté une correction dans la 3.68.



-- 
Jacky Tripoteau

**Comment by brunoc68** [comment]
Le problème se situe après le point 2 : quand on *imprime* la facture, le
numéro de série ne figure pas sur la facture, et il faudrait qu'il y soit.

**Comment by Laurux** [comment]
Le 12/12/2017 à 14:38, brunoc68 a écrit :
> Le problème se situe après le point 2 : quand on *imprime* la facture, le
> numéro de série ne figure pas sur la facture, et il faudrait qu'il y soit.
> 
> 
> Le 12 décembre 2017 à 14:13, Laurux <notifications@github.com> a écrit :
> 
>  > Le 12/12/2017 à 10:50, brunoc68 a écrit :
>  > > === Laurux 3.67.11 ===
>  > >
>  > > Quand on saisie une commande de matériel puis qu'on la convertit en
>  > > facture, on doit rappeler le matériel pour saisir le numéro de série ;
>  > > mais on ne voit pas le numéro de série sur la facture.
>  > >
>  > > Attention : le problème ne se produit pas quand on saisit 
> directement la
>  > > facture avec le matériel : le numéro de série apparaît bien sur la
>  > facture.
>  >
>  > OK, vu.
>  > 1- On passe une commande d'un matériel, il n'y a pas de saisie de numéro
>  > de saisie.
>  > 2- On transforme la commande en BL ou facture, on doit saisir le numéro
>  > de saisie. La fiche du matériel passe en vendu avec les coordonnées du
>  > client.
>  > 3- Si on retransforme le BL ou la facture en commande, le matériel reste
>  > en vendu. Il est alors normal qu'il n'apparaissent plus en BL.
>  > Il faut alors aller dans la fiche du matériel pour le décocher
>  > manuellement.
>  > Je pense que ce fonctionnement restera comme ça car il n'y a pas de
>  > raison de passer un BL ou une facture en commande.
>  >
>  > Cependant en suppression d'un matériel dans un BL ou Facture la fiche du
>  > matériel n'était pas mise à jour. J'ai apporté une correction dans la 
> 3.68.

Je pense que s'il n'apparait pas sur la facture c'est qu'il n'est pas 
présent dans les lignes de BL.
L'impression est une copie fidèle des lignes à l'écran.
Peux-tu vérifier ça STP ?

-- 
Jacky Tripoteau
