### ISSUE TITLE
Logo sur les mails

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#120]
Lors de l'envoi de facture par mail le logo n’apparaît plus.
Forum : https://www.laurux.fr/drupal/node/219

**Comment by Laurux** [comment]
Il faut cocher l'option dans les préférences
Paramètres ==> Préférences ==> Logo ==> Impression du logo sur les courriels

**Comment by damscot** [comment]
@patrick confirme que l'option corrige le pb si oui,
clos le ticket.

**Comment by PatrickMag** [comment]
Je confirme le pb est réglé
