### ISSUE TITLE
Numero de lot en trésorerie

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#121]
En saisie de trésorerie (client) avec lettrage si le numéro de lot n'est pas renseigné le programme plante, ce numéro vient de la facture ... il ne devrait pas être a null.
Forum : https://www.laurux.fr/drupal/node/234

**Comment by damscot** [comment]
apres verification sur master en changeant manuellement la base de donnée 
en mettant numlot et numdoc à NULL, il n'y a pas de pb...
le programme rale juste que numdoc est vide avant d'enregistrer la ligne ce qui est normal.

je propose comme fix pour eviter que le champ soit a null est de proposer le numéro d'ecriture comme numdoc/numlot en mode auto si on a rien saisi dans ce champ... c'est déjà un numéro unique.

**Comment by PatrickMag** [comment]
Oui ça évitera déjà que le programme ne plante, j'avoue avoir un peu de mal à saisir la logique du lettrage
