### ISSUE TITLE
BUG - Impossible de supprimer une ligne en facture d'entretien

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#122]
Version 3.68.2 9eeed5d

Dans une facture d'entretien, il est impossible de supprimer une ligne d'un devis :
- sélection de la ligne
- taper sur la touche SUPR
- message d'avertissement habituel
- confirmation
- la ligne n'est pas effacée

**Comment by damscot** [comment]
@PatrickMag utilise Fix #122 et non pas Fix**e** #122...
la version francaise ne marche pas
