### ISSUE TITLE
Recherche d'un montant qui prend trop de temps

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#123]
Version 3.68.2 9eeed5d

La recherche d'un montant dans Comptabilité / Extrait de compte / Recherche d'un montant
prend désormais jusqu'à 10 minutes sur la base en question, ce qui rend cette fonctionnalité inutiliable alors qu'elle est nécessaire.

**Comment by PatrickMag** [comment]
Bruno il faudra essayer pour voir si l'optimisation de la recherche que j'ai fait fonctionne correctement sur ta base.

**Comment by brunoc68** [comment]
Comment je fais pour récupérer ton optimisation ?

**Comment by PatrickMag** [comment]
La même procédure en changeant l'adresse internet par : https://github.com/PatrickMag/Laurux.git

**Comment by damscot** [comment]
As-tu fais une mise à jour de gambas ? je ne me souviens pas qu'il y ai des
modifs qui est été fait sur ce module entre 3.68.1 et 3.68.2.
j'aurais du mal a expliquer les limitations de performance.
Attention les performances sont forcément dépendant du nombre d'écriture
présente dans les tables.
Damien.

2018-06-19 17:50 GMT+02:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Je suis parti dans l'idée que la base était importante, j'ai donc fait : 
  * Lecture des seuls comptes mouvementés => Économie d'une boucle 
  * Sélection des colonnes à lire 
  * Simplification des clauses where
Il est évident que si la base est trop importante il faudra du temps.

**Comment by Laurux** [comment]
Je viens de regarder le programme. Pourquoi impliquer deux boucles ? D'abord pour le type de compte et ensuite pour les écritures. Il vaudrait mieux faire une seule requète contenant le type de compte.
Je vais regarder ça.

**Comment by PatrickMag** [comment]
@Laurux avant de modifier regarde ce que j'ai fait sur mon repo : 65dee448522297900e13140aa5b0579c6c587b5d
J'ai fait aussi des modifs sur le #124 et #118 qui ne sont pas apparus quand je les ai poussé.

**Comment by Laurux** [comment]
Si je met une jointure sur mvt et comptes alors l'affichage est instantané pour une table de 41400 enregistrements

**Comment by PatrickMag** [comment]
C'est dommage que tu n'ai pas fait un cherry pick sur mon commit .... la principale différence entre nos 2 versions est que tu as fait un left join et moi un inner join même si la construction des requêtes n'est pas identique, il y avait 3 lignes à modifier chez moi pour que l'on ai le même résultat.
Maintenant il faut que j'attende que Damien est mergé nos modifications pour que je puisse les récupérer et en plus ça va générer pleins de conflits ... embêtants à régler et parfois source d'erreur.

**Comment by Laurux** [comment]
Bizarre Patrick. Quant je suis allez voir ton repo il n'y avait rien de changé par rapport à l'ancienne version. C'est pour ça que j'ai poussé mes modifs.
Quels conflits cela peut-il générer ?

**Comment by PatrickMag** [comment]
Tiens bizarre si tu clique sur le lien de commit que j'ai mis au dessus tu as toutes mes modifs ?
Si on modifie tous les 2 les mêmes lignes d'une même classe lors de la rebase ça affiche un conflit que Damien doit résoudre  ... et je me dit que des fois il doit s'arracher les cheveux.

**Comment by Laurux** [comment]
Effectivement, je vois bien tes modifs maintenant. Pourquoi ne les ai-je pas vu avant ?
Quant on fait une modif peut-etre serait-il préférable de clore le sujet pour éviter qu'une autre personne intervienne ?

**Comment by PatrickMag** [comment]
Lorsque on référence une issue  dans le fils de discutions  il y a par exemple : 
PatrickMag added a commit to PatrickMag/Laurux that referenced this issue 12 days ago
@PatrickMag
Suppression d'une ligne en facture entretien : LigblM n'etait pas pri…
2479ad8 
Et l'issue se clôt automatiquement à la rebase.
J'ai voulu référencer 2 issues avec 1 commit et apparemment ça fonctionne pas ... ou j'ai pas fait comme il faut.
