### ISSUE TITLE
BUG code famille lors de la création d'un article

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#128]
Lors de la création d'un nouvel article, lorsque l'on renseigne la famille, le comportement n'est pas le même selon que :
- l'on sélectionne la famille dans le menu déroulant : les caractéristiques de la famille (taux de remise, coefficient de vente) sont remplies automatiquement (= comportement correct)
- l'on inscrive directement le code famille puis TAB (on ne passe pas par le menu déroulant) : il manque des éléments

**Comment by PatrickMag** [comment]
Je ne vois que le taux de remise comme élément manquant,  @brunoc68 peux tu le confirmer ?

**Comment by brunoc68** [comment]
Je n'ai pas testé les autres choses, c'est effectivement le taux de remise qui posait problème.
