### ISSUE TITLE
Mise à jour fiche client dans le module commercial

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#13]
=== Laurux 3.67.11 ===

La case "mise à jour fiche client" quand on édite un document (BL, etc...) ne fonctionne pas si l'on imprime pas le document.

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:52, brunoc68 a écrit :
> === Laurux 3.67.11 ===
> 
> La case "mise à jour fiche client" quand on édite un document (BL, 
> etc...) ne fonctionne pas si l'on imprime pas le document.

Qu'on on active ce bouton il faut cliquer sur le bouton "enregistrer".
NB : Si on passe en lignes de bon, l'enregistrement se fait 
automatiquement.


-- 
Jacky Tripoteau

**Comment by damscot** [comment]
jacky regarde si tu peux faire quelque chose sur master sinon clos le ticket
