### ISSUE TITLE
BUG rappel des lignes de matériel lors du passage d'une commande à une facture

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#132]
Lors du passage du statut "Commande" à "Facture" (et uniquement ce passage), Laurux demande à rappeler les lignes de matériel. En faisant la manip, le numéro de série reste "non attribué" sur le document, alors que l'affectation du propriétaire est bien prise en compte dans la table des matériels

Contournement possible : supprimer la ligne et la refaire lorsque le document est en état "facture".

**Comment by damscot** [comment]
je ne reproduis pas le pb sur Master :
de Commande a Facture, même comportement que de commande à Bon.
le rappelé de ligne et l'attribution du numéro de série fonctionne.

je t'envoie une capture faite par kazam pour te monter.

**Comment by brunoc68** [comment]
Je maintiens que j'ai le problème : je propose de tester la prochaine release quand elle est prèete avant que tu lances en production.

**Comment by damscot** [comment]
je te renvoie la video faite via kazam de mon test sur ma version,
peux tu me faire passer le même genre de capture de ton ecran qui montre le pb.

**Comment by brunoc68** [comment]
Le problème n'est plus là suite au passage à la 3.68.3
