### ISSUE TITLE
Facture : Remise et ecotaxe

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#134]
Remonté du forum : https://www.laurux.fr/drupal/node/275
Lorsque l'on applique une remise sur un article qui a une écotaxe (ici TEA) le total de facture et l'écriture comptable sont  faux, l'écotaxe est rajouté au lieu d'être incluse. La facture elle est éditée correctement .

**Comment by damscot** [comment]
Pb vu sur Laurux ou Laurux-Pos ?

**Comment by PatrickMag** [comment]
Sur Laurux, et en faite même sans remise c'est faux.

**Comment by damscot** [comment]
Fix trouvé par contre si on met sur le meme article une ligne DEE, une ligne DEA et une ligne Copie Privé... ca ne marche pas du tout. la gestion des "blocs" n'est pas du tout bien fait dans le module facturation.
