### ISSUE TITLE
Facture  exonérée :

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#135]
Lorsque on coche la case Exo en facturation le montant de tva se calcul quand même l'édition se fait correctement mais l'écriture comptable est fausse
Forum : https://www.laurux.fr/drupal/node/290

**Comment by damscot** [comment]
Impossible de reproduire, @PatrickMag tu as pu le reproduire dans quelle condition?

**Comment by damscot** [comment]
sur master

2018-08-15 17:25 GMT+02:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Je viens réessayer sur mon ordi de travail (donc 3.68.2) et ça fonctionne, je ne comprend pas sur mon ordi de développement j'ai des cas ou la tva n'est pas à 0 ... même base (sauvegarde) même façon de faire.

**Comment by damscot** [comment]
interressant... c'est peut etre le cas du bug remonter sur le forum.
Tu peux creuser un peu le cas de ton ordi de developpement (fichier de
conf) notamment,
différence de commit etc...

Damien.

**Comment by damscot** [comment]
je pense avoir compris si tu utilise un client X sans EXO et que tu rentre les articles
puis tu change pour un autre client qui lui doit avoir l'exoneration, le fait de cliquer sur Exo ne met pas à jour les lignes déjà saisie... il est meme possible de changer en cours d'edition du BL le mode d'exo il n'y a pas de protection, le fait de devoir mettre ces options avant de saisir les articles c'est pas clair du tout.

ceci m'a permis aussi de regarder egalement l'option saisie facture en TTC, @PatrickMag  @Laurux je sais pas comment doit fonctionner cette fonction mais ca ne marche pas bien du tout et encore moins si tu met l'option exo en meme temps... il y a du ménage a faire la dedans, qu'en pensez vous ?

**Comment by PatrickMag** [comment]
Oui ça je l'avais vu, mais il doit y avoir un autre cas ... il ressortira bien un jour.
Tant qu'a faire le ménage dans tout ça, l'idée est sans aucun doute bonne mais sa mise en place demande une réflexion beaucoup plus approfondie. Personnellement je n'ai pas utilisé toutes les options de la facturation  ni leurs interactions, sans compter que les options ont aussi un impacte sur les factures fin de mois voir même sur la réédition (archive).
Il faudrait se faire une réunion a nous 3 pour poser des objectifs et définir ce qui est raisonnablement possible.

**Comment by damscot** [comment]
en attendant est-ce que je ferme le ticket?
