### ISSUE TITLE
BUG - table des matériels : incohérence due au double enregistrement

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#136]
Il est possible dans la table des matériels d'enregistrer deux fois un matériel avec le même code et le même numéro de série, le second enregistrement écrasant le premier. Cela génère un gros problème, en particulier quand l'utilisateur affecte le 2e enregistrement à un autre client.

En effet, dans ce cas, il s'en suit une incohérence au niveau des fiches ateliers qui ont été créées avec le premier enregistrement : on se retrouve avec le 2e enregistrement et du coup une machine qui appartient à un autre client !

NB : comment l'utilisateur se retrouve avec 2 matériels même code et même no de série : avec un code général "SAV" pour les prises en charge de matériel qu'il n'a pas vendu et un mauvais suivi de la liste des no de série à attribuer...

**Comment by damscot** [comment]
en 3.68.2, il y a un message d'erreur en cas d'attribution d'un numero de série existant. je n'arrive pas a reproduire (voir capture ecran).

peux tu nous fournir une video de ton ecran pour reproduire le pb...

@brunoc68 merci de prendre bien soins a l'ecriture des bugs.
un bug = un moyen de le reproduire (description de la méthode précise, quel menu, quel enchainement d'operation,...), puis si on reproduit pas une base + un fichier de conf.

![kazam_screenshot_00000](https://user-images.githubusercontent.com/14265181/44435434-45e0fd00-a5b0-11e8-8a4f-ebfbcb6e9c03.png)

**Comment by brunoc68** [comment]
J'obtiens bien le message d'erreur "ce numéro de série est déjà attribué..." lorsque je crée un article en tapant sur le bouton CREER.

Mais dans cette fenêtre le bouton CREER est tout à fait optionnel !

Ainsi quand j'arrive dans la table des matériels, il suffit de compléter les champs et de cliquer sur ENREGISTRER pour créer un nouveau matériel, ou pire écraser un ancien numéro de série sans le message d'avertissement.

Je confirme donc le bug avec la précision suivante : il ne se produit que lorsque l'on ne clique pas sur CREER. En fait, je pense que le vrai bug est de pouvoir créer un matériel sans cliquer sur le bouton CREER.

**Comment by damscot** [comment]
la seule manière de corriger cela est de bloquer la modification du numéro de série d'un enregistrement déjà effectué. En cas d'erreur du numéro de série saisie à la création, il faudra alors le supprimer puis le recrée.
