### ISSUE TITLE
L'historique de vente dans la fenetre article doublon pour clients comptes et facture caisse

### ISSUE THREAD

**Issue by damscot** [Laurux/Laurux#139]
Dans l'historique de vente dans l'affichage des articles (DocVentes dans TriHisto)
on recherche les tickets et les factures (dont la facture caisse) = doublon caisse
et les tickets et les bls = doublon client compte

@PatrickMag toi qui a bossé sur la gestion des stocks tu veux regarder ce ticket ou je m'en occupe ?

**Comment by damscot** [comment]
il y a meme des doublons sur des articles avec HT et TTC, peut etre lié au ligne "T", "A", avec un article en eco taxe ou autre type de ligne je pense que le pb est le même, ca utilise typel <> "C" (commentaire)

**Comment by PatrickMag** [comment]
Oui je regarde

**Comment by PatrickMag** [comment]
La solution que je vois est de ne pas afficher les tickets de caisse, d'une part l'historique sera moins longue à afficher et d'autre part il me parait difficile d'identifier une facture/bl issue de la caisse si on voulait ne pas afficher les factures.
Il manquerait les produits composés dans les sorties, est ce judicieux de les rajouter ?
Ils ne sont plus en stock puisque ils composent un autre produit mais pas obligatoirement vendus.

**Comment by damscot** [comment]
c'est vrai que le traitement sur les tickets serait plus long... ceci dit j'ai eu parfois des doutes sur la justesse de la facture de caisse (article remisé ou pas, prix moyen de vente, qte d'article sous forme fraction, etc...), il faudrait peut etre que l'on rajoute une comparaison du total de cette facture vs le livre de caisse, on pourrait meme faire une facture différente par numéro de caisse.
 
Pour les erreurs de stocks le controle sur les tickets peux avoir du sens mais celui-ci peut etre fait avec les fenetres de gestion->stat->Qte article vendus sur une période.

du coup ok pour virer les tickets des stats de vente dans la fenetre article.
Je te laisse faire le commit.

**Comment by damscot** [comment]
c'est correct avec les ventes sur notre article "café".

Le ven. 21 sept. 2018 à 11:21, MAGUER Patrick <notifications@github.com> a
écrit :
