### ISSUE TITLE
sortie version 3.68

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#14]
Une prévision de date de sortie pour la version 3.68 ?

**Comment by damscot** [comment]
probablement fin de cette année, avant le 1er janvier c'est sur!
j'espère que d'ici la l'association aura été crée pour fournir les
attestations au membre au plus vite.


2017-12-13 11:12 GMT+01:00 Laurux <notifications@github.com>:

**Comment by Laurux** [comment]
Le 13/12/2017 à 22:50, damscot a écrit :
> probablement fin de cette année, avant le 1er janvier c'est sur!
> j'espère que d'ici la l'association aura été crée pour fournir les
> attestations au membre au plus vite.

Ben je croyais qu'elle était déjà créée. Y'a un problème ?


-- 
Jacky Tripoteau

**Comment by damscot** [comment]
non pas vraiment de pb,

mais on a pas fini la phase de bug fix interne... on en a trouvé un bon
nombre, mais le merge
de toute les fonctions n'ont pas été testé, il reste pas mal de pb dans les
"modif" de patrick.

de mon coté j'ai pas fini les tests sur la caisse (ticket en attente,
client compte, etc...).

Damien.

**Comment by damscot** [comment]
ca y'est c'est sorti !!
