### ISSUE TITLE
maj (enhancement ?)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#141]
Lors de la mise à jour de Laurux : 

Laurux indique de redémarrer, puis on se retrouve dans le même écran juste avant la mise à jour. C'est assez déroutant : on a l'impression qu'il y a eu un problème et qu'il faille recommencer.

**Comment by damscot** [comment]
ceci permet d'eviter lors de mises à jour simple de redemarrer Laurux. 
Pour le debug lors de pb de mise à jour c'est aussi assez pratique.
j'ai changé le message pour etre plus clair.

**Comment by damscot** [comment]
fix in d245bdbcc62c7e45c828a8ae65630651b6b447be
