### ISSUE TITLE
bug : perte des couleurs 3.68.3

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#142]
Lors d'une installation en réseau, je copie d'un ordinateur à l'autre le fichier de configuration.

Quand l'adresse du serveur MySQL n'est pas la même (par ex. localhost pour le serveur lui-même et 192.168.0.11 pour un poste client) et que je ne pense pas à faire la modif manuellement, au lancement de Laurux on me demande de rentrer les paramètres pour la connexion à la base de données.

Les préférences de couleurs sont alors perdues.

Je n'ai pas vérifié : 
- j'imagine que le problème se produit sur n'importe quelle installation du moment que l'adresse du serveur MySQL renseignée est mauvaise
- il y a peut-être d'autres paramétrages qui sont perdus lors d'une telle opération

**Comment by damscot** [comment]
effectivement en cas de pb de connection, on relance la mise en place des préférences par défaut
c'est tres vieux et j'ai jamais trop compris a quoi ca sert... probablement permettre a quelqu'un qui a mis n'importe quoi dans son fichier de conf de pouvoir s'en sortir avec les paramètres par défaut, car l'edition depuis la console est source d'erreur.
Il faudrait probablement mettre ici aussi un warning... globalement les fichiers de conf sont sauvegardés dans les archivages.

pour éviter les pb d'adresse, n'utilise pas localhost ou l'adresse IP mais plutot des noms avec un service local DNS.

**Comment by brunoc68** [comment]
Le soucis est que cette erreur arrive fréquemment quand on fonctionne en réseau : switch ou serveur éteint et boum plus de connexion + perte de la config.

Ne faudrait-il pas plutôt un bouton qui permette de rétablir les valeurs par défaut ?
