### ISSUE TITLE
bug : rappel des matériels

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#144]
Dans la 3.68.3, lors du rappel des lignes de matériel (passage de Devis/Commande à BL/Facture) pour entrer le numéro de série, le logiciel plante au moment où l'on valide le numéro de série.

Il n'y a pas de problème lorsque l'on établit un BL ou une facture directement, c'est uniquement quand on rappelle une ligne de matériel suite à la transformation du document.

Seul contournement possible : lors du passage BL->Facture, supprimer la ligne puis la refaire et rentrer alors le numéro de série.

**Comment by brunoc68** [comment]
Rien de spécial, mais le plantage a lieu uniquement lors de la validation du no de série.

**Comment by damscot** [comment]
bruno fait une video qui montre l'operation merci

**Comment by damscot** [comment]
ca ressemble beaucoup au bug #132 que l'on avait déjà clos non, car non reproduisible sur 3.68.3

**Comment by brunoc68** [comment]
J'ai rendez-vous cette semaine chez l'utilisateur, je m'occupe de faire une vidéo.

**Comment by damscot** [comment]
aucune nouvelle de ta part sur ce bug. je vais sortir la 3.68.4 sans adresser ce pb.

**Comment by brunoc68** [comment]
Laisse-moi encore aujourd'hui pour te faire la vidéo.

**Comment by brunoc68** [comment]
Je reviens de chez le commerçant, le bug n'est plus là.
J'ai vérifié le log des interventions sur ce cas : 
- maj Laurux en 3.68.3 le 10.10.2018
- bug enregistré le 30.10.2018
- forçage de la maj de la base de données le 15.11.2018
- plus de bug aujourd'hui le 19.12.2018
Je suppose donc que c'était dû à une incohérence version bdd - version de Laurux

**Comment by brunoc68** [comment]
Le bug est toujours là : j'ai réussi à en faire une vidéo ! Je l'envoie en mp avec la base.
La seule différence que j'ai trouvée avec mes manips d'hier : le matériel en question présente une écotaxe.

**Comment by brunoc68** [comment]
A noter : lors de ce crash, le stock de l'article est incrémenté de 1
Le recalcul du stock permet de revenir à la valeur avant le crash.
