### ISSUE TITLE
bug : historique des ventes / achats

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#149]
Laurux 3.68.3

Sur la fiche article dans l'onglet stock, il y a les boutons historique des achats et historiques des ventes.

Dans chacun de ces historiques, on peut sélectionner 1 an (par défaut), 2,3,4 et 5 ans. Par défaut (1 an), l'historique affiche (et comptabilise) les mouvements exceptionnels. Mais pour 5 ans, les sorties exceptionnelles ne sont plus visibles (et pas comptabilisées).

**Comment by PatrickMag** [comment]
Les factures d'entretiens ne sont pas prises en compte dans les listes des ventes. Les mouvements sont pris en compte à n-5 à la date >= au  31/12/2013 (à aujourd'hui).
