### ISSUE TITLE
Historique des ventes : no des BL au lieu des numéros de facture

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#150]
Version 3.68.3

Dans l'historique des ventes, c'est de nouveau les numéros de BL qui apparaissent à la place des numéros de factures (résurgence d'un ancien bug ?).

Ce uniquement pour les factures non archivées. Est-ce un bug ou fait exprès ? Si c'est voulu, quelle en est la raison ?

**Comment by PatrickMag** [comment]
Fixé par le commit 00b2ebf208f604a1bab3923012049db507d21e3f
