### ISSUE TITLE
Ecriture caisse

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#151]
Lors du moulinage l'écriture générée est fausse, HT et TVA.

**Comment by PatrickMag** [comment]
@damscot Tu pourra vérifier que mon fix règle bien le problème, il doit avoir un certain nombre d'écritures fausses ... que faut il faire ?

**Comment by damscot** [comment]
patrick j'ai fais un peu différement de ton commit pour eviter une recopie de code pour la gestion de l'historique tiquet.
j'ai commité la suppression de Raz Tables (tres mauvaise pratique de créer les tables non temporaire dans le code hors fonction de MAJ, rien de mieux pour faire des bases incohérentes)

je vais regarder comment faire un programme de correction des ecritures... mais ca va etre chaud car il faut retrouver les règlements de BL (en facture archivées) faite en caisse pour corriger proprement les ventilations sur les différents compte de vente/tva, et regarder toutes les tickets avec les supports de remise... gros boulot. je vais me concentrer sur ce pb si tu veux bien regarder les autres tickets merci.
