### ISSUE TITLE
erreur sur log.close

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#18]
On ne peut plus changer de société. On a une erreur sur le log.close de la sub Close()

**Comment by damscot** [comment]
je ne suis pas sur de comprendre comment la gestion multisociete fonctionne... lorsque l'on duplique la societe, la table fiche_societe n'est pas dupliqué comment alors passer de l'une a l'autre a moins que les 2 sociétés soit présentes dans les deux tables fiches_societe.

lorsque l'on cree une nouvelle base comment met on a jour les fiches societe de chaque base pour toujours permettre le basculement entre chaque societe.

**Comment by Laurux** [comment]
Pour changer de société on passe par la tables sociétés et on sélectionne la société voulue en cliquant dessus.
Le programme Fsoc utilise le composant db.databases pour récuper les sociétés. Regarde la sub Init_base()
Pour créer une nouvelle société on passe par la table des sociétés et on clique sur "créer" avant de remplir les zones. La société est créée avec des tables vierges hormis la table Fiches_Soc qui elle contiendra les données qu'on vient de saisir. On a ensuite la possibilité de dupliquer une societé.

**Comment by Laurux** [comment]
je pense avoir fermé un peu vite

**Comment by damscot** [comment]
Jacky je vais pousser un fix assez complet sur la gestion multisociété. A tester stp.

J'ai notamment supprimer la partie creation des tables dans Fsoc (qui avait de nombreuses erreur et est trop difficile a maintenir) pour m'appuyer sur la database par défaut Laurux01.sql, qui est utilisé lors de la creation de la société initiale... du coup c'est plus simple et ca utilise partout la même mecanique.
j'ai mis a jour Laurux01.sql pour creer des sociétés en avec le premier exercice en 2018 (on est a 1 jour de 2018).

**Comment by damscot** [comment]
je pense avoir corrigé le bug... j'ai essayé plus de pb.

2017-12-30 11:00 GMT+01:00 Laurux <notifications@github.com>:
