### ISSUE TITLE
kill lock

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#19]
dans *start on a une ligne 122 qui kill le lock ce qui fait qu'on peut ouvrir plusieurs instances sans avoir de message d'avertissement.

**Comment by damscot** [comment]
C'est Fixé ici:

Fix 5172a2ef9d1a4bad8f518b3ece2d04e5ba99e737

ca sera mis dans la 3.68.1

2017-12-29 11:38 GMT+01:00 Laurux <notifications@github.com>:
