### ISSUE TITLE
Validation des receptions marchandise

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#20]
- Une requête avec un sum(champ) retourne toujours un résultat aivable, donc erreur sur le passage des écritures de consigne en comptabilité.
- Dans l'édition du récapitulatif la variable libel ne doit pas avoir plus de 30 caractères.
- La validation d'un avoir laisse la somme du collectif en négatif.

**Comment by Laurux** [comment]
Un avoir est toujours négatif. je ne comprends pas ta logique Patrick.

**Comment by PatrickMag** [comment]
La même logique que toi Jacky, c'est ce que tu a fait quelques lignes plus bas pour les comptes fournisseurs.
En - au crédit ou en + au débit, ici en + au débit.
Le soucis est quand tu veux clôturer ton exercice la balance est déséquilibrée.

**Comment by Laurux** [comment]
Oups ! Moi y'en avoir mal compris ce que toi me dire la première fois.
