### ISSUE TITLE
Base de démarrage

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#23]
Ou se trouve la base de démarrage, la base vierge qui se trouvait avant sous ~/Laurux3 ?
Car sans cette base on ne peut pas débuter avec Laurux.

**Comment by damscot** [comment]
elle est intégré au binaire Laurux, je vais la mettre a jour avec la
version 3.68, car du coup à la création d'une nouvelle société elle a une
version trop ancienne.
je vais fixé ca pour la 3.68.1

2017-12-30 15:21 GMT+01:00 Laurux <notifications@github.com>:
