### ISSUE TITLE
Tarif Fioul

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#25]
Erreur sur la gestion des tarifs fioul 
#25df92411223cacd8b2b9e699c39cbc94fcbbf99

**Comment by damscot** [comment]
Patrick tous tes fixs sont dans master,
tu peux faire un
git fetch laurux
git pull --rebase laurux master

klk infos:
- sur tes commits, n'utilise pas la premiere ligne de ton message de commit
pour les clore les tiquets
met plutot ca dans la deuxième ligne de ton commit. La premiere ligne sert
a mettre une description textuelle.

- utilise plutot Fix #25 que #sha1 pour clore le tiquet quand le commit est
mis dans master.

- je sais pas ce que tu as fait sur ta branche v3.69 mais c'est une sorte
de rebase de ma v3.69 sur ta branche master ou alors un cherry pick de mon
commit... c'est pas bien!!
pour corriger fait
git fetch laurux
git checkout v3.69
git reset --hard laurux v3.69
git push -f origin v3.69
puis reviens sur master
git checkout master

merci de tester la duplication de societe... j'ai fait beaucoup de fix
Damien.


2017-12-30 17:33 GMT+01:00 PatrickMag <notifications@github.com>:
