### ISSUE TITLE
Erreur de date sur les éditions d'inventaire articles non saisies

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#28]
Une qui reste du passage à gambas 3.1 certainement.

**Comment by PatrickMag** [comment]
@damscot La modif est référencée au dessus, ça ne suffit pas ?

**Comment by damscot** [comment]
Patrick ce que je dis c'est que si tu avais mis dans le commit
72be9c11e8d7fdf08d657ae9335328b2475b8a3f
le message suivant:
1ere ligne:  Erreur de date sur les éditions d'inventaire articles non
saisies
2eme ligne: Fix #28

le commit une fois poussé sur master clos le ticket automatiquement, si le
ticket est associé au projet v3.68, il fait alors évoluer la barre de
progression,
et la reference du ticket est rajouté dans le log du ticket (il n'y a
aucune opération à faire sur github du coup)

Damien.


2018-01-09 7:56 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
D'accord mais c'est dommage c’était plus simple ... pour moi et tant que tu parle de la fonction projet, je n'y est pas accès non plus.

**Comment by damscot** [comment]
le pb de mettre Fix #28 c'est que bien sur cela clôt le ticket mais,
depuis git en ligne de commande ou git-cola impossible de comprendre ce que
fait le fix sans regarder le code ou se connecter sur github.

pour affecter les labels, j'ai demandé a jacky de te rajouter comme
contributeur du repo officiel, je n'ai pas vu d'autre solution dans github.

Damien

2018-01-09 8:40 GMT+01:00 PatrickMag <notifications@github.com>:
