### ISSUE TITLE
recalcul des stocks - critique !

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#31]
Bonjour,

Je viens de passer sur la 3.68 : le recalcul des stocks ne fonctionne plus du tout.

Stock réel : 58
Stock théorique : 61
Stock initial = 127
Total ventes = 340
Total achats = 273
On remarque déjà que 127-340+273=60 et non pas 61 : c'est le soucis historique, les stocks ne collent pas. Mais jusqu'à présent on pouvait lancer un recalcul des stocks et arriver à peu près au bon résultat.

Mais avec la 3.68, le recalcul des stocks, juste pour la référence, me fait passer le stock théorique à 187 (sic).

Du coup, impossible d'utiliser la 3.68, en particulier durant la période d'inventaire...

PS : je suggère de renommer dans la fiches articles onglet stock les boutons suivants :
- Histo ventes -> sorties
- Histo achats -> entrées

**Comment by Laurux** [comment]
Bonjour,
on va faire comme d'habitude.
Une sauvegarde SVP avec le produit concerné.

**Comment by brunoc68** [comment]
Avant d'envoyer une sauvegarde, question : je reçois cette demande d'une
adresse @reply.github.com

Dois-je répondre à cette adresse ?

Les données étant confidentielles, il ne faudrait pas qu'elle se retrouve
sur github...




2018-01-05 15:08 GMT+01:00 Laurux <notifications@github.com>:

**Comment by Laurux** [comment]
jscops at wanadoo point fr

**Comment by Laurux** [comment]
Pourrai-je avoir une référence produit SVP ?

**Comment by brunoc68** [comment]
BOUB4LM

**Comment by Laurux** [comment]
C'est le code prit en exemple plus haut ? Car les données ne correspondent pas.

**Comment by brunoc68** [comment]
Oui c'est le code pris plus haut.
Nous avons juste fait une entrée et une sortie manuelle de 100 unités à chaque fois pour tester. Il faut aussi compter que la sauvegarde de la base a été faite après le recalcul du stock.

**Comment by damscot** [comment]
j'ai fait un recalcul des stocks sur l'article correspondant
et ca me retourne bien 60... il vient d'ou le calcul de ton stock théorique?

**Comment by damscot** [comment]
sachant qu'a la restoration de ta base de donnée l'article avait 187 en stock.

**Comment by brunoc68** [comment]
C'est bien ce que j'ai écrit : après recalcul du stock, j'ai obtenu 187, alors que :
- au début il y avait 61
- le calcul manuel me donne 60 (stock initial - total ventes + total achats)
- le stock réel est de 58

**Comment by damscot** [comment]
est-ce que tu as pu vérifier avec cette base et gambas 3.10.0?
Chez moi le recalcul de stock donne bien 60.

Damien...

2018-01-07 9:47 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by brunoc68** [comment]
Je viens de mettre gambas 3.10.0 sur la debian 8 (avec toujours Laurux 3.68.0) :
- désinstallation de 3.5.2-2+b1 livré avec la distrib
- recompilation

Recalcul des stocks : 184

**Comment by brunoc68** [comment]
Je viens de réimporter la base (stock = 184) sur mon PC de test avec 3.67.11 : le recalcul du stock me donne bien 60.
Je remets la base avant recalcul (stock = 184)
Je mets gambas 3.10.0
Je fais la mise à jour et reparamètre la connexion à la base
Le recalcul du stock me laisse à 184

Questions : la version de Laurux avec laquelle tu obtiens 60 est-elle bien celle que l'on obtient avec la maj automatique ?

Ce qui est sûr c'est que l'on tient là enfin quelque chose : même version de Laurux et même version de Gambas qui donnent 2 calculs de stock différents avec la même base !
Quoi d'autre qui peut changer entre les 2 distribs ?

**Comment by brunoc68** [comment]
Peux-tu me donner la requête SQL correspondante, histoire de voir directement dans la base si le calcul sort correctement ?

**Comment by damscot** [comment]
Bon tu as bien fait de me demander si j'avais testé avec la version v3.68.0... en fait j'utilise master, convaincu que le bug était toujours là car addressé par personne.... en fait @Laurux (jacky) l'a corriger sans clore le ticket probablement car il n' a pas fait le lien... j'ai essayé de cherry-pické juste le commit a373bdcbbdcc072028a26741a39effe7509cda4d par dessus la v3.68.0 (avec lequel je reproduis le pb en fait) et le pb est corrigé dans master et donc kd la v3.68.1 sortira.

**Comment by brunoc68** [comment]
Damien, je vois que tu arrives à avoir les corrections qui sont en cours : il faut que tu m'expliques comment faire cela parce que je ne peux pas attendre davantage la 3.68.1, nous sommes bloqués.

**Comment by damscot** [comment]
il y a encore beaucoup d'activité par jacky/patrick pour les fix. je pense
que l'on est pas encore pret pour la v3.68.1 peut etre fin de semaine
en attendant je te conseille de générer toi même ta version de test:

la première fois
git clone https://github.com/Laurux/Laurux.git

puis à chaque besoin (attention tu seras sur master... ca peut planter
sévère... il n'y a aucun test automatique):
----
cd Laurux
make clean
git reset --hard origin master (pour t'aligner sur les dernier
developpement)
make package
tu trouveras le Laurux.tar.gz dans .hidden/Stable/v3.68.0/Laurux.tar.gz
---

decompresse le tar.gz sur le home comme une installation standard.

Damien.

2018-01-10 9:36 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by brunoc68** [comment]
Damien,

J'ai fait comme tu m'as dit à une exception : "git reset --hard origin
master" ne fonctionne pas donc j'ai fait "git reset origin master"

Je poste depuis 2 jours des bugs en indiquant la version e7bd408 qui a
résulté de cette compilation.

Sauf que la version e7bd408 est la version officielle 3.68.0, donc on ne
peut pas faire la différence avec ma version compilée...

Bruno

**Comment by brunoc68** [comment]
Autant pour moi c'est moi qui ait fait une erreur ! J'obtiens 0990d6b après recompilation.

**Comment by damscot** [comment]
n'hesite pas a faire sur ta version d'essai (pas de production)
git reset --hard origin/master (avec le /... je l'oublie tout le temps)
make clean && make (dans le "a propos" de Laurux tu trouvera le sha1 de la
version compilé)

comme ca tu vérifes que les tickets que l'on clot sont bien corrigé.
Damien.

2018-01-12 11:00 GMT+01:00 brunoc68 <notifications@github.com>:
