### ISSUE TITLE
Matériel - impossible de modifier la ligne

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#32]
v3.68

Dans un devis, une facture, etc...

Quand on rappelle une ligne de matériel et qu'on modifie quelque chose (prix, remise, etc...) et que l'on enregistre : la modification n'est pas prise en compte (il n'y a pas de message d'erreur non plus).

**Comment by Laurux** [comment]
Jusqu'à présent, il fallait supprimer la ligne et la resaisir avec les bonnes données. 
Je ne sais pas si ce fonctionnement est bien orthodoxe mais c'est ainsi.

**Comment by brunoc68** [comment]
Je confirme que cette méthode fonctionne.

Il faut supprimer la ligne matériel puis la ligne de commentaire.

A noter que contrairement à la version 3.67.11 il reste un soucis : le no de série n'est plus disponible lors de la resaisie !

**Comment by Laurux** [comment]
Je vais voir ça avec la sauvegarde car chez moi ça fonctionne correctement y compris pour la ligne du numéro de série qui s'efface automatiquement.

**Comment by brunoc68** [comment]
Je propose de fermer ce bug car dupliqué en #33
