### ISSUE TITLE
matériel et numéro de série

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#33]
v3.68
Il s'agit d'un bug qui est revenu en 3.68 alors qu'il avait été corrigé en 3.67.11

Quand on rappelle une ligne de matériel, le logiciel demande de resaisir le numéro de série. Or le numéro de série n'est plus disponible.

**Comment by Laurux** [comment]
Ce qui a été corrigé dans la 3.67 c'est la suppression du matériel qui ne mettait pas à jour la fiche matériel. En principe on ne modifie pas une ligne de matériel on la supprime et on la resaisi

**Comment by brunoc68** [comment]
Suppression et resaisie fonctionne.

La modification des lignes de matériel fonctionnait avant la 3.67.11 (certain !) ; elle avait d'ailleurs été optimisée suite à nos retours parce que justement le no de série n'était plus disponible lors de la modification, comme aujourd'hui avec la 3.68

Aujourd'hui avec la 3.68, le logiciel nous laisse modifier la ligne, bien qu'il ne tienne pas compte de nos modifications. Mais lors de l'enregistrement des modifications, le logiciel demande de resaisir le no de série : il n'est alors plus disponible.

Etape pour reproduire les bugs :
- créer un BL
- ajouter un matériel : saisie du no de série
- reéditer la ligne
- modification du prix
- enregistrement
- demande de saisie du no de série
-> blocage car no de série plus disponible
