### ISSUE TITLE
suppression d'une ligne de matériel - ligne numéro de série reste

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#34]
v3.68

Quand on ajoute un matériel, il y a une ligne de commentaire avec le numéro de série qui s'inscrit.
Quand on supprime le matériel, la ligne de commentaire no de série reste : il faut la sélectionner et la supprimer elle aussi.

**Comment by Laurux** [comment]
Je ne constate rien de tel.

**Comment by brunoc68** [comment]
- création d'un devis
- ajout d'une ligne matériel : on trouve le matériel et une ligne commentaire "numéro de série non attribué"
- suppression du matériel
-> la ligne de commentaire "numéro de série non attribué" est encore là

**Comment by Laurux** [comment]
Ah ! OK.
Ca sera corrigé dans la prochaine maj.

**Comment by damscot** [comment]
jacky quand tu commit le fix de ce ticket,
il faut ajouter "Fix #34" dans la deuxième ligne du commit
ca fermera automatiquement le ticket quand il sera poussé sur master
et cela permet d'associer un commit à ce ticket... c'est plus propre.
