### ISSUE TITLE
Devis entretien

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#35]
Dans la fenêtre facture d'entretien, l'onglet "Estimation" donne à l'impression "Devis".

Ne serait-il pas préférable de laisse "Devis" à la place d'"Estimation" comme pour les factures normales ?

**Comment by Laurux** [comment]
OK, ca sera corrigé dans la prochaine mise à jour.
En entrtien de matériel, comme pour les véhicules, on parle d'estimation mais pas de devis car le devis à une valeur contractuelle que n'a pas l'estimation, ce qui mermet de ne pas être engagé lors d'une mauvaise découverte pendant un démontage.

**Comment by brunoc68** [comment]
Je pensais que Devis irait mieux parce que c'est le pendant de la partie Facturation classique.
Maintenant s'il vaut mieux Estimation pour le côté juridique j'adhère ; simplement dans ce cas il faudrait avoir aussi Estimation à l'impression.

**Comment by Laurux** [comment]
Ca sera fait dans la prochaine maj
