### ISSUE TITLE
Crash ouverture facture v3.67.11 puis 3.68

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#36]
J'ai une facture (non imprimée) qui m'a provoqué un crash en v3.67.11
Le document est locké à partir d'un PC en particulier : message d'alerte normal depuis les autres PC comme quoi le document est utilisé.
Quand j'essaie d'ouvrir la facture depuis le PC en question, j'ai un crash de Laurux avec le message :

[13] null object.
Facture.Recup_ligbl.2326

J'ai fait la mise à jour en v3.68 : le problème persiste.

**Comment by Laurux** [comment]
Il me faudrait une sauvegarde pour voir ce qu'il y a.

**Comment by Laurux** [comment]
OK, ca sera corrigé dans la prochaine maj.
