### ISSUE TITLE
Perte du fichier de configuration lors de la migration 3.67.11->3.68

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#37]
Le fichier de configuration n'a pas été récupéré en lançant une maj depuis le logiciel directement.

**Comment by damscot** [comment]
logiquement le fichier de conf est déplacer de
~/.config/gambas/Laurux3.conf à ~/.config/gambas/Laurux.conf
peux tu nous lister les fichiers présent dans ~/.config/gambas

2018-01-05 15:05 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by damscot** [comment]
Tu peux donner les précisions demandé Bruno?

**Comment by brunoc68** [comment]
pc01@PC01:~$ ls -al ~/.config/gambas
ls: impossible d'accéder à /home/pc01/.config/gambas: Aucun fichier ou dossier de ce type

pc01@PC01:~$ ls -al ~/.config/gambas3
total 36
drwxr-xr-x  2 pc01 users 4096 janv.  9 12:13 .
drwx------ 24 pc01 users 4096 oct.  11 09:15 ..
-rw-r--r--  1 pc01 users  546 janv.  9 12:04 gambas3.conf
-rw-r--r--  1 pc01 users 1110 févr. 15  2017 Laurux3(1).conf
-rw-r--r--  1 pc01 users 3377 janv.  9 10:46 Laurux3.conf
-rw-r--r--  1 pc01 users 1306 mars  13  2017 Laurux3_majStockEspace.conf
-rw-r--r--  1 pc01 users 1088 mars  13  2017 Laurux3_majStockSansEspaceUniquement.conf
-rw-r--r--  1 pc01 users  620 mars  15  2017 Laurux3-pos.conf
-rw-r--r--  1 pc01 users 2690 janv.  9 12:13 Laurux.conf

**Comment by damscot** [comment]
peux tu faire un diff entre le fichier Laurux.conf et Laurux3.conf
que l'on vérifie les différences.

le déplacement semble avoir lieu au moins sur la première mise à jour
puisque le fichier Laurux.conf existe... si tu restore la v3.67 et que tu
rejoue la mise a jour, le warning
est normal car on ne peut pas vérifier qu'il n'y a pas eu de modification
sur les fichiers de conf entre temps. l'utilisateur doit vérifier les
données.

Damien.

2018-01-09 12:13 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by brunoc68** [comment]
diff Laurux3.conf Laurux.conf :

0a1
> # Laurux local configuration
7,8c8,9
< Coulfonds="255;255;255;"
< Others="255;255;255;"
---
> Coulfonds="255,252,216,"
> Others="255,232,199,"
11,12c12,13
< Facts="Background: &H67D004&; Font: serif,9; "
< Avs="Background: &HFF0000&; Font: serif,9; "
---
> Facts="Background: &HFFFFFF&; Font: Serif,9; "
> Avs="Background: &HFFFFFF&; Font: Serif,9; "
14c15
< Devis="Background: &HFFFF7F&; Font: serif,9; "
---
> Devis="Background: &HFFFFFF&; Font: Serif,9; "
24a26
> Soc="01"
27,29c29
< Soc="01"
< intitule="ETS NUNNINGER"
< LastTip=23
---
> LastTip=5
33,56d32
< Compression=0
< Affmaj=1
< 
< [Soc]
< Entete=1
< Conditions=1
< Tva550=0
< Codetva=" "
< Compta=0
< Gestion=0
< CptFac=1
< Qt1=0
< Coul_fen=0
< Ctrlstk=0
< AutoEnt=0
< Font="Serif,+1"
< Copie=0
< Siret="Siret"
< Prxdec=0
< Slide=1
< Taxe="TVA"
< Exp=1
< Lettrage=1
< Impbl=0
73a50
> Slide=-1
75,76c52,55
< Pays="France"
< Impbl=-1
---
> nbfam="5"
> ipr=[5]
> pp=False
> bois=False
78,79d56
< Tme=0
< Slide=0
83c60,72
< Libdevis=0
---
> Materiel=-1
> Depots=0
> Ged=0
> Taches=0
> Franchise=0
> Pvcons=0
> Analytique=0
> Lettrage=-1
> Carte=0
> Cheque=0
> Caisse=0
> Coef=True
> Tmq=False
86a76,88
> prixRecpt=-1
> Rcptman=0
> NumBr=0
> Depannage=0
> Libdevis=0
> Rglt=-1
> Poids=0
> Marge=0
> MO=0
> CodeMO="1 "
> ServerLogIP="127.0.0.1"
> ServerLogPort=6556
> Tme=0
91,92d92
< Coef=True
< Tmq=False
98,100d97
< Rglt=-1
< Poids=0
< Kgl=0
102,107d98
< Materiel=-1
< Depots=0
< Ged=0
< Taches=0
< Franchise=0
< Pvcons=0
120,121c111
< Caisse=-1
< Fht=0
---
> Fht=-1
123,125c113
< Marge=0
< MO=0
< CodeMO="1 "
---
> Impbl=-1
132,135d119
< Analytique=0
< Lettrage=-1
< Carte=0
< Cheque=0
140d123
< Depannage=0
143a127
> AffClient=0
145,146d128
< prixRecpt=-1
< Rcptman=0
148,161d129
< Pied=-1
< Imp2L=0
< Col=-1
< ChxImp=0
< BlA5=0
< Impstocke=0
< ImpPDF=0
< ImpTotbl=0
< NumBr=0
< Prgmail="Icedove"
< SelDev=True
< Expfact="1"
< Statcamo=-1
< Fecran="fond_ABCRESEAU.jpg"
168d135
< Cond=0
170a138,150
> Pied=-1
> Imp2L=0
> Col=-1
> BlA5=0
> Impstocke=0
> ImpPDF=0
> ImpTotbl=0
> Cond=0
> Statcamo=0
> Pays="France"
> Expfact="1"
> Prgmail="Icedove"
> Fecran="Laurux2.jpg"
174,175d153
< LcolE="col0:95;col1:90;col2:290;col3:102;col4:100;col5:100;col6:120;col7:86;col8:79;col9:80"
< LcolRA="col0:75;col1:130;col2:240;col3:87;col4:100;col5:80;col6:100;col7:84;col8:103"
177,185c155
< LcolC="col0:69;col1:140;col2:290;col3:100;col4:76;col5:100;col6:60;col7:100;col8:30"
< LcolT="col0:81;col1:240;col2:110;col3:110;col4:110;col5:110;col6:300"
< LcolP="col0:70;col1:90;col2:210;col3:100;col4:100;col5:100;col6:100;col7:60;col8:71;col9:34"
< LcolH="col0:66;col1:140;col2:260;col3:100;col4:68;col5:100;col6:66;col7:100;col8:178"
< LcolS="col0:34;col1:80;col2:260;col3:109;col4:100;col5:110;col6:80"
< LcolTL="col0:43;col1:80;col2:100;col3:111;col4:90;col5:240;col6:80;col7:80;col8:70;col9:33"
< 
< [Societes]
< Soc01="Laurux V3.59"
---
> LcolE="col0:95;col1:90;col2:290;col3:100;col4:100;col5:100;col6:120;col7:70;col8:60;col9:60"
193c163
< Host="192.168.0.1"
---
> Host="localhost"
196d165
< Version="Laurux V3.59"

**Comment by brunoc68** [comment]
Question : le fichier de conf est-il sensé récupérer les paramètres ? Si oui nous sommes dans le cas d'un soucis général lié à ma distribution où les choses ne se passent pas comme sur la tienne (Damien).

**Comment by brunoc68** [comment]
Je viens de retester une migration v3.67.11 -> v3.68.0 avec la base que je vous ai envoyée sur mon PC de test (toujours une Debian 8 et cette fois avec gambas 3.10.0 dès le départ) :
- pas de message d'erreur
- fichier Laurux.conf créé mais vierge
- Laurux3.conf n'a pas été touché

Question : le nouveau fichier Laurux.conf doit-il être une simple copie de l'ancien fichier Laurux3.conf ?

**Comment by damscot** [comment]
voici le code de la mise a jour du fichier .conf...

If Exist(User.Home & "/.config/gambas3/Laurux3.conf")
    If Not Exist(User.Home & "/.config/gambas3/" & Application.Name &
".conf")
      Move User.Home & "/.config/gambas3/Laurux3.conf" To User.Home &
"/.config/gambas3/" & Application.Name & ".conf"
    Else
      Message.Warning("Warning Maj368 n'a pas déplacé les fichiers de conf,
car la source et la destination existent!\nVeuillez verifier manuellement
les configurations!\n source: " & User.Home &
"/.config/gambas3/Laurux3.conf\n destination: " & User.Home &
"/.config/gambas3/" & Application.Name & ".conf")
    Endif
  Endif


Le code parle pour lui meme c'est un move simple... du coup les fichiers
devrait etre les même apres mise à jour exepté certain nouveau paramètres
qui sont ajouter au prochain démarrage de Laurux... il ne devrait pas y
avoir autant de différence apres mise à jour...
tu confirmes que tu n'as pas le message de warning décrit dans le code
ci-dessus?

Damien

**Comment by brunoc68** [comment]
Je confirme : pas de warning et nouveau fichier vide.

**Comment by damscot** [comment]
Est ce que tu as renommer le binaire ?
Il se nomme bien "Laurux"... a priori oui vu le nom de ton nouveau fichier
de conf.

**Comment by brunoc68** [comment]
Non je n'ai pas renommé le binaire, c'est bien "Laurux" pour la v3.68.0
Il m'arrive juste de faire des copies des fichiers de conf en ajoutant la date au nom de fichier.

**Comment by damscot** [comment]
peux tu m'envoyer une base 3.67.11 et votre fichier de conf en 3.67.11 que
j'essaye de mon coté.

**Comment by brunoc68** [comment]
Je m'en occupe aujourd'hui : récupération des sauvegardes, confirmation de mon côté, et je t'envoie tout ça quand c'est reproductible chez moi.

**Comment by brunoc68** [comment]
Envoyé.

**Comment by damscot** [comment]
ok je viens de comprendre ce qu'il se passe...
on demarre en 3.67.11 avec binaire Laurux3.gambas & Laurux3.conf
on passe en 3.68.0 avec binaire Laurux & Laurux.conf.... pour faire la Maj on a besoin d'avoir la connection à la base de donnée du coup il recherche Laurux.conf pour trouver le user/passwd, comme il trouve pas le fichier, il demande de créer un fichier de conf (qui sera cree par défault "vide")
une fois la connection faite il rentre dans le logiciel mais ne fait pas la mise à jour (je sais pas pourquoi encore)..
ensuite au prochain démarrage il fait la mise a jour en v3.68 mais envoie le message de warning car les deux fichiers existent et du coup ne fait pas la copie et conserve le fichier "vide"

je pense que la strategie (car c'est un sac de noeux) à la mise à jour de 3.67 a 3.68 de conserver le fichier Laurux3.conf, de passer le fichier "vide" Laurux.conf en Laurux.conf.bak avec un petit message et de recopier Laurux3.conf vers Laurux.conf.

**Comment by brunoc68** [comment]
De ce que tu dis le workaround est tout simple, dis-moi si je me trompe :
- on fait la mise à jour et on sort
- on écrase Laurux.conf ainsi créé par Laurux3.conf
- on rentre dans Laurux

**Comment by damscot** [comment]
oui... je suis en train de faire un fix pour faciliter la maj depuis 3.67

**Comment by Laurux** [comment]
Ok, un simple cp suffira.
