### ISSUE TITLE
Erreur lors de l'impression de facture v3.68

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#39]
A l'impression d'une facture, on obtient la fenêtre d'erreur :

Query failed:Table 'Fiches_Journaux' was not locked with LOCK TABLES
DB_Connection.Exec.277

La facture est tout de même imprimée, et en cliquant sur OK on peut continuer à utiliser le logiciel.

**Comment by Laurux** [comment]
Le numéro de facture SVP car je n'arrive pas a reproduire.

**Comment by brunoc68** [comment]
Le problème survient sur une configuration réseau avec à peu près toutes les factures...

**Comment by PatrickMag** [comment]
L'erreur est dans les factures fin de mois ?

**Comment by damscot** [comment]
quand tu parles d'installation reseau... je vois pas le rapport avec le lock Table,
que tu sois en utilisation réseau ou monoposte le lock est fait de la même manière.

... je n'arrive pas a reproduire sauf un pb effectivement en facture fin de mois (merci patrick)

**Comment by brunoc68** [comment]
Je confirme que c'est avec les factures normales.

Le problème vient peut-être de la base décelée comme corrompue par Jacky ?

**Comment by Laurux** [comment]
Le réseau ...
Il est possible que vos tracas viennent de là.
Pouvez-vous nous expliquer comment le réseau a été mis en place SVP concernant notamment le déploiement de laurux.

**Comment by brunoc68** [comment]
Installation sur chaque poste (identique) avec base de donnée sur le serveur.
Version 3.68 : le fichier de conf n'ayant manifestement pas été récupéré, j'ai recoché les options qui étaient désactivée (gestion du matériel) et reparamétré la connexion à la base de données, sur chaque poste.

**Comment by PatrickMag** [comment]
Il faut aussi remettre le nom et chemin des fichiers.

**Comment by brunoc68** [comment]
C'est à dire ?

**Comment by PatrickMag** [comment]
Dans préférence local onglet "PDF"
En faite il faudrait revérifier tous les onglets.

**Comment by PatrickMag** [comment]
Autre solution à essayer : 
Renommer Laurux3.conf en Laurux.conf
Relancer Laurux
Aller dans les préférences locales => vérifier (gestion(3) familles entre autre)
Fermer Laurux 
Et voir si ça marche.

**Comment by brunoc68** [comment]
Merci de me donner des informations pour que je comprenne ce qu'on me demande de faire. Est-ce juste de dire :
- le fichier de configuration jusqu'à la version 3.67.11 était ~/.config/gambas3/Laurux3.conf
- le nouveau fichier de configuration avec la version 3.68.0 est ~/.config/gambas3/Laurux.conf
- le passage 3.67.11 -> 3.68.0 aurait dû renommer (copier, effacer ?) Laurux3.conf en Laurux.conf

Concernant les préférences PDF : il n'y avait rien avant, il n'y a rien maintenant. Du coup les pdfs vont dans ~/Impressions qui semble être le répertoire par défaut.

**Comment by PatrickMag** [comment]
Chez moi  j'ai du re-indiquer les chemins de stockage, lors des éditions de facture ça me générais une erreur (facture fin de mois).
Ici le but est de s'assurer que dans la configuration ancienne et nouvelle il n'y a pas de différence.

**Comment by brunoc68** [comment]
Ok donc pas de différence car dans les 2 cas les champs étaient vides...

**Comment by brunoc68** [comment]
Précisions :
- le message d'erreur apparaît uniquement lors de la première impression, c'est à dire lors de la conversion en facture définitive
- ans le cas présent, il s'agit de facture avec saisie des règlements : les règlements apparaissent bien dans les statistiques

**Comment by PatrickMag** [comment]
Vu, j'envoie la modif

**Comment by PatrickMag** [comment]
Attention : Sur les factures qui ont généré cette erreur, les règlements comptables ne sont pas passés => voir les extraits de compte.
