### ISSUE TITLE
Parametres

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#40]
Lors de la duplication d'une société on perd l'index de Fiches_parametres, ça provoque une erreur au moins dans le moulinage des tickets.

**Comment by damscot** [comment]
il n'y a pas de raison d'utiliser l'index dans la fiche société car il ne
doit y avoir q'une seule société par database, du coup il vaut mieux
virer ce champ dans l'utilisation du moulinage.

Damien.

**Comment by PatrickMag** [comment]
C'est fait mais du coup on ne peux plus utiliser db.edit sur le fichier des paramètres.

**Comment by damscot** [comment]
ok, j'ai pas implementé le hook de capture d'acces pour db.edit... c'est
utilisé souvent?
si c'est utilse comme API on peut conserver l'index et forcer l'utilisation
de l'index 0.

2018-01-06 17:43 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Oups j'avais mal lu, non pour le moment ce n'est pas utilisé souvent et ne nécessite pas de développements supplémentaires, je ferais mes modifs dans la 3.69.

**Comment by damscot** [comment]
Ok peux tu faire un rebase de ta branche sur "laurux master" que je puisse poussé ce fix sur master sans perturber jacky.
git fetch laurux
git pull --rebase laurux master
git push -f origin/master*
merci
