### ISSUE TITLE
pb de saisie d'ecriture comptable avec des lignes similaires

### ISSUE THREAD

**Issue by damscot** [Laurux/Laurux#41]
produire des ecritures comptable avec le même
compte,numdoc,numero produit un crash en
-releve de compte/facture
-ne cree pas de sha1 sur certaine ligne... vu dans la base de brunoc

**Comment by Laurux** [comment]
Damien,
j'ai corrigé le bug du relevé et je peux le pousser si tu veux.

**Comment by damscot** [comment]
ok, il faut vérifer qu'il n'y a pas d'autre pb sur l'affichage des
écritures et à la clôture de l'exercice.
mais oui pousse le et met dans le message de commit sur la deuxième ligne F
i x 40 avec # devant

2018-01-08 15:48 GMT+01:00 Laurux <notifications@github.com>:

**Comment by Laurux** [comment]
fix #0ae68fa

**Comment by damscot** [comment]
la reecriture du commit donne maintenant ce sha1:
269431b825fb1f271896f7588f934bf096168898

attention jacky quand je dis qu'il faut mettre fix #numero ... c'est dans le message du commit qui fixe le pb, pas dans le corps du message ci-dessus dans github.
