### ISSUE TITLE
Réception manuelle de matériel - impossible d'enregistrer no série v3.68

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#44]
Bloquant avec le module Gestion du matériel :

Lors de la réception manuelle d'un matériel, le logiciel demande d'enregistrer le no de série.
1. l'affichage n'est pas correct : le numéro saisi est superposé sur le reste de la fenêtre
2. l'enregistrement ne fonctionne pas, il est indiqué que le numéro existe déjà (ce qui n'est pas le cas j'ai vérifié) ; en outre il est proposé de remplacer, etc... et les options ne foncitonne pas non plus

**Comment by brunoc68** [comment]
Update : nous n'avons pas trouvé de workaround -> bug critique...

**Comment by damscot** [comment]
peux -tu faire quelque capture d'écran... je ne vois pas de quoi tu parles en reception manuelle de matériel (pour moi c'est saisie facture entretien mais je me trompe peux etre).
Damien.

**Comment by brunoc68** [comment]
Non c'est pas dans les factures d'entretien, c'est vraiment "Réception manuelle" sous les "commandes fournisseurs". C'est là que tu enregistres le matériel qu'on te livre.

**Comment by damscot** [comment]
peux tu donner un exemple, je n'arrive pas a produire le cas ou lors d'une reception, il demande l'ajout d'un numéro de serie (j'y connais rien en gestion matériel)

**Comment by Laurux** [comment]
Cela a été corrigé il y a 4 ou 5 jours.
c40c2b9

**Comment by brunoc68** [comment]
Comment puis-je avoir accès à cette correction, n'étant pas un utilisateur averti de github ?

**Comment by brunoc68** [comment]
Je ne suis pas encore à l'aise avec gambas, mais en parcourant rapidement le fix j'ai l'impression qu'il ne s'agit que d'une correction au niveau de l'aspect de la fenêtre ?

Je précise bien que lorsque l'utilisateur saisit un no de série (malgré l'apparence bizarre), il obtient un message d'erreur et ça ne fonctionne pas.

**Comment by damscot** [comment]
5c55cc7ab79d6d91237ea977c23d385013bb18b1
en addition a celui de jacky... ca semble fixer!
a reouvrir sinon.
