### ISSUE TITLE
Reclassement des devis/BL/facture après édition des lignes v3.68.0

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#46]
Suite à l'édition d'un document ("lignes bon"), le classement des documents revient systématiquement dans l'ordre alphabétique des noms de clients, quel que soit le classement qu'il y avait avant de rentrer dans l'édition.
Ce n'est pas bloquant mais c'est gênant, d'autant que ce classement par défaut change d'une version à l'autre de Laurux.
Il faudrait qu'au retour de l'édition d'un document, l'utilisateur se retrouve avec la même présentation qu'avant l'édition.

**Comment by Laurux** [comment]
Bonjour Bruno,
c'est vraiment bizarre ce qu'il se passe chez toi ou alors je comprends mal ton problème.
Si je télécharge la version du site (3.68.0 e7bd408 branche master) on garde le tri préalablement sélectionné.
Peux-tu nous donner la version complète STP (sous le format indiqué plus haut)

**Comment by Laurux** [comment]
Par contre je viens de voir que le problème existait à la sortie des lignes de bon. 
Je vais corrigé ça.

**Comment by brunoc68** [comment]
Oui c'est cela : à la sortie des lignes du bon.

**Comment by Laurux** [comment]
C'est corrigé
