### ISSUE TITLE
pb liste des documents en cours - il manque des dates dans les plages de dates - v3.68.0

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#47]
Dans le menu Gestion / Facturation / Liste des documents en cours :
Quand on indique une plage de dates (par exemple du 01.01.2018 au 09.01.2018) il manque des dates sur le résultat pdf. En fonction de la plage indiquée, certains jours apparaissent puis disparaissent.

**Comment by Laurux** [comment]
Il faudrait contrôler en facturation que les documents sans date n'aient effectivement pas de date.

**Comment by damscot** [comment]
je ne vois pas le pb des  jours qui apparaissent puis disparaissent
le pb que je vois est la plage de selection des comptes clients (c'est moi qui est rajouté cette feature)
si on ne met rien on utilise les comptes par défaut:
  Dim cli_start As String = "411001"
  Dim cli_end As String = "411999"
en fait vu la taille de la société il faudrait mettre 41199999 en compte de fin par défaut.
si tu cree une selection sur le range complet des comptes clients le bug est contourné.

**Comment by brunoc68** [comment]
Je suggère de réouvrir cet issue : en effet si on ne met rien dans le champs, on part du principe que tout doit être pris, et il faudrait que ce soit le comportement par défaut.

J'ai vérifié : le fait de mettre 41199999 dans le range fonctionne. Il s'agit ici d'un workaround, mais pas vraiment d'une résolution de bug...

**Comment by damscot** [comment]
ce ticket est fixé dans le commit
Fix 1a91eddf24340ddbe5392af3ec1db514f184f4fe

Il est dans master
