### ISSUE TITLE
pb liste des documents en cours / touche F2 - v3.68.0

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#48]
Dans le menu Gestion / Facturation / Liste des documents en cours : la touche F2 pour choisir la date ouvre bien un calendrier, mais on ne peut pas sélectionner de date.

**Comment by Laurux** [comment]
Tu fais bien un double-clic pour sélectionner la date ?

**Comment by brunoc68** [comment]
Double clic et je sors du calendrier, mais la date ne s'inscrit dans le champ prévu.

**Comment by PatrickMag** [comment]
Exact, mais le double clic fonctionne => double clic dans le champ date et la sélection fonctionne.

**Comment by brunoc68** [comment]
Exact : double clic pour ouvrir le calendrier puis double clic pour sélectionner la date foncitonne
Par contre F2 pour ouvrir le calendrier puis double clic sur la date ne fonctionne pas
-> bug ultra-mineur ultra-low-priority

**Comment by Laurux** [comment]
OK, le bug est corrigé.
