### ISSUE TITLE
Bordereaux des règlements - le même règlement ressort à 2 dates différentes - v3.68.0

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#49]
Dans le menu Gestion / Facturation / Bordereaux des règlements, certains règlements apparaissent en double.
Exemple dans la base envoyée : Mr Keller facture no 2018006164. Le même règlement pour la même facture apparaît à la date du 01.01.2018 et à la date du 02.01.2018.

**Comment by Laurux** [comment]
Pour la journée du 01.01.2018 je n'ai aucun mouvement par contre sur le 02 j'ai bien la facture avec un règlement par espèces.

**Comment by brunoc68** [comment]
Désolé : le même règlement apparait le 02.01 et le 03.01

**Comment by Laurux** [comment]
OK Bruno, c'est corrigé
