### ISSUE TITLE
no BL à la place du no de Facture dans Fiche article / stock / historique des ventes

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#5]
Laurux3 version 3.67.4 et 3.67.10

Dans l'historique des ventes (Fiche article / stock) il était indiqué soit le BL, soit le no de facture si elle aviat été imprimée. Désormais il n'y a que le no de BL, même quand la facture a été imprimée.

**Comment by damscot** [comment]
Pas vu de pb sur la branche de developpement en utilisant la base client
voir screenshot ci-dessous (article TU180):

![histo_vente](https://user-images.githubusercontent.com/14265181/32413526-3ac4c7e8-c213-11e7-8893-e9126bea3c14.png)

si tu as un screenshot a partager.
Damien.

**Comment by Laurux** [comment]
Ok, voilà .
C'est corrigé dans la jacky_v3.68 (entre autres choses)
[https://share.orange.fr/#JGhNsUVqD4be6d13a07](url)

**Comment by damscot** [comment]
jacky quand tu fix une issue, utilise la methode de git...
tu met dans la deuxième ligne de ton commit
Fix #(num de l'issue)
soit Fix #5 ici.

l'issue sera clot automatiquement avec la référence sha1 du commit qui le fixe.

Damien.

**Comment by Laurux** [comment]
En fait j'ai pas voulu fermer. J'ai du appuyer ou il fallait pas.

**Comment by damscot** [comment]
du coup si tu as fait un fix... personnellement je n'ai pas vu de pb dans
la branche v3.68
n'hésite pas a "amender" ton commit pour rajouter dans les commentaire le
mot clé "fix #5"
pour clore le ticket automatiquement avec ton fix.

Damien.

2017-11-05 12:09 GMT+01:00 Laurux <notifications@github.com>:
