### ISSUE TITLE
Bug Impression commande fournisseur

### ISSUE THREAD

**Issue by damscot** [Laurux/Laurux#50]
Pris sur le forum : 
[Impression commande fournisseur](https://laurux.fr/drupal/node/101)

Bonjour,
En commande fournisseur il ne se passe rien quand je clique sur Ies boutons Imprimer et Mail. Il y a juste 3 bouts de lignes du cadre de la fenêtre qui apparaissent.

Merci pour votre aide ... et bonne année.

**Comment by Laurux** [comment]
Il faut faire attention avec les forms, j'ai corrigé plusieurs problèmes comme celui-ci.
Si on doit les mettre en arrière plan alors on fait un raise à l'ouverture.
