### ISSUE TITLE
Réception manuelle et saisie direct du code article v3.68.0 (0990d6b branche master)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#52]
En réception manuelle de marchandise, lorsque l'on clique sur la fenêtre de recherche pour retrouver le code, et que l'on sélectionne le code, le curseur se place sur la quantité -> normal.

Mais quand on tape directement le code (sans passer par la fenêtre de recherche) et que l'on appuie sur la touche TAB, le curseur se place sur la case "Qté cmde". Pis, quand on appuie alors sur la touche TAB, le curseur se place sur la case précédente "Stock maxi".

**Comment by PatrickMag** [comment]
C'est déjà corrigé par le sha1: dfe26535ae4cc3e52e6334219753100e391a30d7

**Comment by brunoc68** [comment]
Patrick, j'ai compilé et installé la dernière version comme m'a indiqué Damien. Est-ce que ton fix n'était pas dedans ?

**Comment by PatrickMag** [comment]
Oups ... me suis trompé chef !
J'en ai rectifié que la moitié, du coup tant qu'a faire des erreurs je m'essaye sur les labels ...
