### ISSUE TITLE
Liste des documents en cours v3.68.0 (0990d6b master)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#53]
Dans Gestion / Facturation / Liste des documents en cours :

1. Quand on sélectionne une plage de dates (ex. 01.01.2018 - 10.01.2018) et que l'on demande un classement par date, on obtient dans le désordre :

2018006157 | 02/01/18
2018006159 | 02/01/18
2018006232 | 10/01/18
2018006256 | 03/01/18
2018006182 | 05/01/18
2018006187 | 05/01/18
2018006209 | 06/01/18
2018006195 | 06/01/18
2018006198 | 06/01/18
2018006218 | 09/01/18
2018006229 | 10/01/18

2. Quand on sélectionne une seule date (ex. 10.01.2018 avec la même base que précédemment), je n'obtiens qu'un seul enregistrement.

3. Sachant que sur cette base j'ai 19 documents pour le 10.01.2018.

========= En utilisant le tip de Damien (cf issue #47) ===============

Quand je sélectionne une seule date (ex. 10.01.2018) :
- j'obtiens seulement 18 enregistrements du 10.01.2018 et un enregistrement du 11.01.2018
- les documents sont dans le désordre : facture 28, 29, 35, 30, 31, 41, 22, 23...

Par ailleurs le classement par numéro de document donne exactement le même résultat.

**Comment by damscot** [comment]
je n'arrive pas a reproduire
voici les ordres défini:
  If RadioButton8.value Then Ordre = "numbl"
  If RadioButton9.value Then Ordre = "datebl, numbl"
  If RadioButton10.value Then Ordre = "cdclibl, nmclibl, type, datebl, numbl"
  If RadioButton11.value Then Ordre = "livraison, cdclibl, type, datebl, numbl"
attention c'est le numero de BL qui actuellement pris, le numéro de facture est ignoré...
l'ordre de numérotation des BL est certainement different des numéros de Factures

en utilisant la base que tu nous avais donné, pour le 03.01, je retrouve bien 14 documents.

**Comment by damscot** [comment]
pour le pb date je viens de comprendre en prenant une plage plus large...
pour les type "F" on affiche la date de la facture, alors que le tri est fait sur la date du BL
faudrait voir @Laurux pour comprendre le rationnel de tout ca.

**Comment by Laurux** [comment]
En fait tout se fait a partir du bl, du numéro et de la date. Le numéro de facture n'est là que pour l'affichage.

**Comment by damscot** [comment]
du coup bruno peut t'on clore ce ticket si c'est un comportement normal ?

**Comment by brunoc68** [comment]
Je propose de laisser ouvert (même si faible priorité) pour 2 raisons :
1. le foncitonnement "normal" n'est pas évident du tout
2. dans la mesure où il est possible de ne choisir que les factures, il n'est pas logique dans ce cas de classer par autre chose que les numéros de facture

**Comment by damscot** [comment]
j'ai fait un fix, lorsque l'on choisi les documents de type facture
on utilise la date de la facture et le numéro de facture

si on selectionne tous les documents Devis, BL, facture...
on utilise la date et numero de BL meme pour les factures

**Comment by brunoc68** [comment]
C'est plus logique comme cela. A documenter dans le guide utilisateur sur la statistique en question.
