### ISSUE TITLE
Lock sur document facturation v3.68.0 (e7bd408 master)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#54]
J'ai un lock sur un document Facturation (sur la base envoyée no document 5949). Quand je supprime j'ai un message d'erreur et Laurux plante :
[13] Null object.
Facture.Recup_ligbl.2326
J'ai toujours un lock quand je reviens dans Laurux et je ne peux rien faire de ce document.

Une nouvelle facture aujourd'hui m'a donné le même problème, sauf que cette fois : la suppression a fonctionné sans problème.

Dans les 2 cas la facture avait été saisie avec Laurux 3.68.0 officielle.

A noter que je ne peux pas faire de test sur mon PC test, parce que là j'ai le message locké par un autre utilisateur. Y a-t-il un workaround pour prendre la main sur le document locké par un autre utilisateur comme si l'on était cet autre utilisateur ?

**Comment by brunoc68** [comment]
Autant pour moi et désolé pour vous mes amis : je me suis planté de version.
Il n'y a plus de problème avec la 0990d6b.

Ma remarque précédente reste cependant valable pour le debugging :

Je ne peux pas faire de test sur mon PC test, parce que là j'ai le message locké par un autre utilisateur. Y a-t-il un workaround pour prendre la main sur le document locké par un autre utilisateur comme si l'on était cet autre utilisateur ?

**Comment by PatrickMag** [comment]
Sur un pc de test soit avec phpadmin (je l'utilise pas) soit avec l'IDE de gambas => connexion - a gauche tout en bas => clic droit - nouvelle connexion
Tu repères le fichier Fiches_Docatif et tu supprime la/les ligne qui ne te correspond pas.
En regardant ce fichier je me rend compte qu'il y a plein de blocage concernant les réceptions, c'est pareil chez toi ?

**Comment by brunoc68** [comment]
Je confirme : pareil chez moi, et il s'agit des réceptions récentes cad avec la maj 3.68.0

L'utilisateur ne me signale aucun blocage : forcément il n'y a qu'une seule personne qui fait les réceptions et quasiment tout le temps sur le même PC. Du coup de mon PC test je n'arrive pas à ouvrir le BR car "Lock" -> bug confirmé

Par ailleurs, j'avais déjà remarqué que lors d'une réception manuelle, il y a un bouton "VALIDER LA SAISIE" qui semble ne servir à rien.


Pour info, en MySQL, on fait : select * from Fiches_Docactif;

**Comment by PatrickMag** [comment]
Valider la saisie sert a ... valider la saisie  et passer à la suivante.
Si tu veux le faire dans une fenêtre mysql c'est la bonne syntaxe, après vérification tu pourra faire : 
truncate table Fiches_Docactif;
Ça remet le fichier a 0 => plus de blocages.
Ne serait il pas mieux de clore ce ticket et d'en refaire 1 pour les blocages en réception de marchandise ?

**Comment by brunoc68** [comment]
C'est fait : ticket #55
