### ISSUE TITLE
Modif

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#57]
dans les fork il y a 2 modifs de patrick qui ont été faites dans ma branche. C'est normal ?

**Comment by damscot** [comment]
jacky,
tu n'as pas updater ta branche comme je l'avais indiqué dans un mail:
je redonne la procédure ici

jacky:
--------
(attention commitez et pousser vos modifs en remote dans une nouvelle branche si vous en avez en cours, je les reprendrais sur master après)
git fetch
git checkout fix_jacky-3.68
git reset --hard origin master
git push -f origin fix_jacky-3.68

il y a eu des branches que j'ai du forcer l'update pour faire les rebase entre nous trois... il est donc
tout a fait possible d'avoir des commits des autres utilisateurs dans ta branche de développement (dans ta branche il y nos commits a tous les trois... ici de rebase de ta branche sur la version précédente de master).

tu pense a quels commit en particuiler ?

Damien

**Comment by Laurux** [comment]
Désolé Damien mais j'ai été absent de chez moi quelques jours. Je vais faire ça maintenant
