### ISSUE TITLE
Affichage des tickets

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#58]
Bug remonté du forum sur les affichage des tickets archivés.

**Comment by damscot** [comment]
patrick quand tu fais ce genre d'association met l'url du message du forum
dans le ticket... tu peux faire pareil dans le forum en mettant l'url du
ticket.

2018-01-15 18:27 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by damscot** [comment]
ok tu l'as fait sur le forum manquait juste l"autre moitié :-)

**Comment by damscot** [comment]
@laurux (jacky) j'ai vu que tu as simplifé cette ligne le 11 nov 2017,
effectivement chez moi ca plante aussi, j'avais pas essayé depuis un moment.
tu te rappelle de la raison de cette modif.
dans la base de notre epicerie j'ai des formats de date très variable dans cette base (helas ce champ est au format string au lieu de date.)
tu as une idée comment s'en sortir ?

j'ai des format du type en fonction de la version de Laurux utilisé pour le moulinage:
YYYY-MM-JJ
YYYY-MM-JJ HH-MM
et
YYYYMMJJHHMMSS

**Comment by Laurux** [comment]
Je pense qu'il faudrait passer le champs en datetime. Je vais voir comment c'est possible sans altérer les données.

**Comment by Laurux** [comment]
OK, j'ai fait une modif pour ça, je la pousserai quant tu m'auras débloqué avec la commande git que je t'ai envoyé

**Comment by damscot** [comment]
Oui bien sur on changera le type de format en passant à la v3.69... mais je
pense
pas que l'on puisse faire autrement qu'un contournement du pb en v3.68...
il y a qd même quelques chose que je n'explique pas sur le changement de
format (3 actuellement dans ma base),
J'ai peur que d'autre personne en ont encore plus en fonction des mise à
jour effectuée.

2018-01-16 10:44 GMT+01:00 Laurux <notifications@github.com>:

**Comment by Laurux** [comment]
Tu peux m'envoyer une sauvegarde STP

**Comment by damscot** [comment]
je suis sur la base de bruno actuellement, lorsque je reviens sur la base
de notre épicerie
l'essaye de te mouliner quelque ticket en 3.68.0 et sur master (auparavant
nous avions des tickets en v3.56).

Damien.

2018-01-16 15:36 GMT+01:00 Laurux <notifications@github.com>:

**Comment by brunoc68** [comment]
Pourquoi pas un fix qui détecte le format (string) et qui le convertit en un format unique (string) en attendant que l'on passe le champ en datetime ?

**Comment by Laurux** [comment]
en fait j'ai opté pour ça Bruno dans le commit 856a3e5

**Comment by damscot** [comment]
j'ai tiré ton fix pour faire des essais de mon coté... c'est la galère car depuis la version v3.68 déjà publié un nouveau format de date est du coup introduit. ca plante a plusieurs endroits:
gestion des archives tickets / statistique de ventes / etc... l'affichage des tickets avec tri par date ne fonctionne plus bien du coup puisque le tri est fait dans le requete SQL (c'est pas trop grave) 
je vais pousser ca ce soir...  a tester en détail avec la caisse pour être sur qu'on a pas laissé de gros loup caché.
