### ISSUE TITLE
umask sur répertoire lors de l'utilisation de la GED

### ISSUE THREAD

**Issue by ffrouin** [Laurux/Laurux#7]
Bonjour,

Un usager utilise Laurux avec la GED sur un système de fichier NFS.

Pour permettre à des usagers d'un même groupe système de partager les droits en lecture/écriture sur des fichiers, les usagers ont un MASK de configuré dans leur environnement système : 0002 (équivalent à chmod 664 ou 775).

Les fichiers créés par Laurux ont bien un mask conforme à l'environnement des usagers qui lancent le logiciel.

En revanche, sur tous les répertoires créés, c'est un MASK 0022 (équivalent à chmod 644 ou 755) qui est utilisé par Laurux et qui n'est donc pas conforme à ce qui est configuré dans l'environnement de l'usager (commande utilisée pour configurer et lire le MASK : umask).

Pouvez-vous confirmer si l'application Laurux fait un "reset" du mask ou si elle utilise bien le mask définit via la commande "umask" ?

En vous remerciant,
Bien cordialement,                Freddy.

**Comment by damscot** [comment]
Bonjour,

Il n'y a rien dans les sources de Laurux dans la partie GED sur la variable
d'environnement umask...
le pb est effectivement visible aussi sur tous les repertoires crée par
Laurux...
je pense que le pb vient plutot de gambas que de Laurux.
Il faut fouiller un peu.

Damien.

Le 23 novembre 2017 à 10:57, Freddy Frouin <notifications@github.com> a
écrit :

**Comment by ffrouin** [comment]
Voilà ce que je vois sur le site de Gambas : http://gambaswiki.org/wiki/cat/file mais je ne trouve rien concernant l'utilisation du mask système.

**Comment by Laurux** [comment]
Bonjour,
on devrait donc faire un umask 0002 avant la création ?

**Comment by damscot** [comment]
non umask 0002 n'est pas forcement ce que veux l'utilisateur... C'est un pb
au niveau
gambas et pas laurux. il faudrait poser un ticket sur gambas et associer
kes deux tikets.


2017-11-25 18:42 GMT+01:00 Laurux <notifications@github.com>:

**Comment by damscot** [comment]
http://gambaswiki.org/bugtracker/edit?object=BUG.1216&from=L21haW4-
je pense qu'en attendant la solution peut etre au niveau du paramètrage du montage du disque partagé,
utiliser les setuid flag.
utiliser un cron pour nettoyer les permissions.

si cela ne fonctionne par on pourrait wrapper mkdir autour d'une classe utilisant les settings.
mais je suis pas fan de cette methode.
Damien.

**Comment by damscot** [comment]
Bug posé sur le bugtracker gambas mais benoit ne semble pas convaincu par mes arguments

[http://gambaswiki.org/bugtracker/edit?object=BUG.1216&from=L21haW4-](http://gambaswiki.org/bugtracker/edit?object=BUG.1216&from=L21haW4-)

**Comment by brunoc68** [comment]
J'ai régulièrement des soucis de umask dans autres applications.

La solution bancale mais universelle est de paramétrer iwatch de manière à ce qu'à chaque création de répertoire la commande chmod est exécutée avec les bons paramètres.

**Comment by damscot** [comment]
apres des mois de dialogue de sourd avec benoit de Gambas, il n'y aura pas de changement de gambas sur un suivi equivalent a la commande mkdir du shell. Pour l'instant on ne va pas remplacer toute les appel mkdir de gambas par des mkdir via shell. je propose que l'on ferme le ticket... il est toujours possible de résoudre le pb de droits via linux (ex cron job ou autre, voir ci-dessus.)
je clos le tiquet en wontfix.
