### ISSUE TITLE
Table des matériels - ergonomie difficile Laurux v3.68.1 (1389baf branche: v3.68)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#73]
Dans la table des matériels il y a deux soucis d'ordre pratique. Très gênants mais non bloquants.

Pour choisir un matériel, il est impératif d'ouvrir la liste complète et de naviguer dans cette liste jusqu'à sélectionner la bonne ligne : aucun raccourci habituel ne fonctionne (recherche par code produit, recherche par nom de matériel).

De même dans la fiche matériel, quand on veut sélectionner le propriétaire on doit ouvrir la liste déroulante, trouver et sélectionner la bonne ligne sans possibilité de recherche.

**Comment by damscot** [comment]
@Laurux est-ce que tu voudrais prendre en charge cette amélioration dans le filtrage de la table matériel comme demandé par @brunoc68, si c'est un boulot trop important on peut faire ca plutot dans la v3.69.

**Comment by Laurux** [comment]
Ok pour la recherche du client. Par contre pour la recherche du matériel en facturation, cela est-il indispensable ? En général un client n'a jamais énormément de matériel au point de vouloir faire des recherche autre qu'un simple défilement.
