### ISSUE TITLE
Feature request - création de client avec tous les champs Laurux v3.68.1 (1389baf branche: v3.68)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#74]
Dans le cas présent, lorsque l'on crée un nouveau client il faut qu'on lui assigne le type de client.

Malheureusement on ne sait jamais si le client est déjà enregistré ou pas : on le voit au moment de la facturation.

Du coup, quand il n'est pas déjà dans la base, on doit resortir de la facturation pour aller le créer, ou alors le créer en facturation puis sortir pour aller mettre le type de client.

C'est un cas typique de "factorisation" où il faudrait avoir accès à la même fenêtre de création de client, que l'on soit en facturation ou dans la table client.

**Comment by Laurux** [comment]
En facturation on peut faire F4 pour ouvrir la fenêtre des clients.

**Comment by brunoc68** [comment]
Effectivement ça fonctionne bien avec F4.

**Comment by damscot** [comment]
on devrait peut etre faire appel a F4 quand on clique nouveau client plutot
que d'attriber un nouveau numéro.
et recupérer le client nouvellement crée a la sotie de la table de client.

2018-02-15 8:18 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by Laurux** [comment]
La création directe permet d'être plus rapide.

**Comment by damscot** [comment]
ok si les champs choisi sont suffisant pour ceer un compte,
du coup pour répondre à la problematique de bruno:
il faut :
- rechercher le client dans le toggle button 'code client'
- si il n'y n'existe pas faire Nouveau pour un client standard
- si c'est un client "particulier" faire F4 pour creer un compte complet et
que les tarifs "type client" s'applique dès le premier document


2018-02-28 12:07 GMT+01:00 Laurux <notifications@github.com>:
