### ISSUE TITLE
Facture qui n'apparaît pas en compta

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#76]
Bonjour,

J'ai un soucis avec une facture que je retrouve bien dans la gestion commerciale, mais qui est totalement absente de la comptabilité.

Pourtant il me semble qu'il est impossible de supprimer une telle ligne comptable de facture, je me trompe ?

**Comment by damscot** [comment]
Il est possible de supprimer une ecriture qui n'a pas été lettré, une ecriture lettré peut aussi etre debloqué (menu dans les outils de compta). les ecritures supprimées peuvent etre visible dans impression -> ecriture modifié/supprimée.

Bruno ce genre de question a plus ca place dans le forum... il ne faut pas saturer les tickets github avec des bug/pb non confirmé... je clos le ticket que tu recréera/reouvrira un nouveau si tu as plus d'info (une base, un numéro de facture... etc...).

**Comment by brunoc68** [comment]
Justement Damien, il semble qu'il ne soit pas possible de supprimer une écriture générée automatiquement à la facturation, à la différence des autres écritures générées manuellement. Donc si une telle écriture disparaît, il s'agit bien d'un bug, ou bien ?

Par ailleurs, en faisant ce que tu m'as indiqué (compta / impression / écriture modifiée/supprimée), j'ai trouvé ce qui ressemble à un autre bug : le cas où l'on a supprimé une écriture, puis le compte comptable correspondant (justement parce que le compte était faux). Et bien il est alors impossible d'utiliser cette impression : le logiciel refuse et bloque parce que le compte n'existe pas !

**Comment by damscot** [comment]
comme je te disais meme les ecritures généré automatiquement peuvent etre délocké puis supprimé.
donc si l'ecriture a disparu de la table Mvt c'est pas forcement un bug, par contre si elle est pas dans MvtM c'en est un.

effectivement il est possible que la suppression d'un compte en comptabilité peut poser des pb
a l'affichage des ecritures... il faudrait tester ce cas en détail.

peux tu lister le nombre d'ecriture dans la table MvtM avec le type S.

**Comment by damscot** [comment]
logiquement il est pas possible de supprimer un compte qui a des ecritures dans Mvt, il n'ya peut etre pas de protection pour MvtM.
je sais pas ce qu'il se passe pour les suppressions de compte a travers plusieurs exercice.

@Laurux tu as un avis sur le sujet?

**Comment by Laurux** [comment]
On ne peut pas supprimer un compte utilisé dans les fichiers MvtX.
Je vais regarder pour pour MvtM

**Comment by damscot** [comment]
Jacky le commit Fix #76 ne contient que des modifs sur des commentaires je pense que ce n'est pas celui-ci qui fixe le pb?
est-ce que ton fix est pour la "protection pour MvtM" n'est pas plutot le commit 
8f2cc9b5c6377093252ed923ee5b6383e2fc6741
dans ce cas comme je l'ai indiqué à @PatrickMag il faut si possible faire des commit avec
git commit --fixup <sha1 du commit faux> et fait un git rebase --autosquash -i <sha1 d'avant le/les commit faux> 
puis git push -f

l'idee c'est toujours de progresser avec git ne fait pas de rebase dans ce cas la puisque c'est déjà poussé.

Concernant la protection, dans la pratique comment faux-t-il faire du coup si on veut corriger un compte que l'on a utilisé par erreur sur l'execice courant et/ou sur le/les exercices précédents (comment ne pas le conserver pendant 5 ans). ne faudrait pas t'il pas faire une sorte de fonction de transfert de numero de compte afin de par exemple de changer l'affectation / l'intitulé d'un compte précédement utilisé (modification du plan comptable).

**Comment by Laurux** [comment]
Oui Damien, c'est bien celui là. Mais comme j'avais oublié de mettre le fix et que je n'ai pas trouvé comment le mettre après coup, j'ai juste fait une petite modif cosmétique.
Je pense qu'il faut laisser le compte comme ça, en créer un autre et passer une OD pour solder l'ancien et mettre le solde dans le nouveau. 
Changer la numérotaion va casser la clé de controle.

``git commit --fixup et fait un git rebase --autosquash -i <sha1 d'avant le/les commit faux>
puis git push -f``
C'est trop compliqué pour moi tout ça.

**Comment by PatrickMag** [comment]
On ne doit pas modifier une écriture lorsque le mois est clôture et encore moins lorsque l'année est clôturée, ce n'est pas légal. Il faut faire une OD et si il y a une incidence fiscale (en leur faveur) le déclarer à l’administration.
