### ISSUE TITLE
Fonds d'écran personnalisé - v3.68.1 (1389baf branche v3.68)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#78]
Je n'arrive plus à mettre un fonds d'écran personnalisé : l'image indiquée n'est plus prise en compte.

Remarque : on peut éventuellement penser à supprimer totalement cette fonctionnalité (ainsi que le défilement des fonds d'écran).

**Comment by damscot** [comment]
Duplicated #69
already fixed
