### ISSUE TITLE
Erreurs mysql

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#79]
Patsy a déjà fait remonter plusieurs fois des erreurs dues à la clause group by. Toutes les nouvelles installations sont configurées comme ça et je n'ai pas trouvé de moyen simple pour changer durablement cette dernière.
Que faut il faire, changer les requêtes (pas toutes simples) ou existe t il un autre moyen ?
https://www.laurux.fr/drupal/node/158

**Comment by damscot** [comment]
il faut espérer que cela ne vient pas d'un pb plus profond...

je ne connais pas assez les requetes sql pour savoir ce qu'il faut mieux
faire,
si la nouvelle ecriture fonctionne sur les anciennes version de mysql...
c'est ok sinon il faut masquer cette complexité à travers une
classe... probablement DB.connection qui fait déjà plusieurs choses autour
de requete sql pour sqlite3.

Damien.

**Comment by PatrickMag** [comment]
Oui ça marche avec les anciennes versions, mysql devient moins permissif et se met en conformité avec la norme sql (pour cette partie là du moins) ce qui est une bonne chose si tu veux utiliser un autre moteur.

**Comment by damscot** [comment]
c'est parfait, je conseillerais donc au développeur d'utiliser des
configurations peut permissive pour
corriger un max de pb... connait tu les options les mieux adaptés au niveau
mysql...

pour info mon portage en cours pour sqlite3 dans la 3.69 me pose aussi pas
mal de pb lié à nos ecritures de requetes.

Damien.
