### ISSUE TITLE
Inventaire fin d'année

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#8]
Validinv.class ligne 184 : Utils.db.Exec("Truncate table " & "Fiches_HisInvT" & "")
Fait planter le programme sur une base nouvelle si on a pas exécuter une validation des inventaires tournants avant.
Je pense que la ligne peut être supprimée sans autres conséquences.

**Comment by Laurux** [comment]
Il faut mettre un try devant pour gérer l'erreur.
si on enlève cette ligne la table des historiques des inventaires tournants ne sera jamais effacé or après la validation de l'inventaire de fin d'année on n'a plus besoin des histos en tout cas laurux ne les gère pas.

**Comment by damscot** [comment]
Comme je l'ai déjà dit il est plus propre de tester l'existance de ces tables et de les supprimer après un message de warning si elle existe... du coup pas de Try et une verification complementaire faite.
je t'ai assigné le ticket si tu fais des essais autour de ca...
Il faut assigner les tickets de manière générale, sinon on sait pas qui fait le boulot.
