### ISSUE TITLE
"Une mise à jour de patch est disponible"

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#80]
Pour le passage de la v3.68.0 à v3.68.1, on obtient le message indiqué en sujet.

Le mot patch n'est pas clair pour les novices, il faudrait trouver autre chose : à discuter lors de la prochaine réunion ?

**Comment by damscot** [comment]
c'est effectivement un language classique en informatique
majeur(3).minor(68).patch(1)

fait une proposition dans le ticket.

**Comment by brunoc68** [comment]
Je propose "une mise à jour est diponible" en enlevant "de patch".

**Comment by damscot** [comment]
comment distinguer alors des mise à jour impliquant ou non des changements de base de données.
compatibilité entre version de meme niveau de "patch" pas pour des version mineures.
regarde [Version Logiciel](https://fr.wikipedia.org/wiki/Version_d%27un_logiciel)

certain parle de "version de maintenance", c'est pas plus clair pour moi...
peut etre
mise à jour de correction/correctif pour "patch"
mise à jour de version pour "majeur.mineur"
