### ISSUE TITLE
Recalcul des stocks défectueux v3.68.1 (6157158 branche master)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#81]
Je viens de migrer de 3.67.11 à 3.68.0 puis 3.68.1. Les stocks étaient à peu près stabilisés en 3.67.11 et surtout le recalcul des stocks foncitonnait.

Mais en 3.68.1, l'outil recalcul des stocks ne fonctionne pas :
- stock départ 0
- Histo ventes 242
- Histo achats 360

Stock après recalcul des stocks : 182 au lieu de 118

Hyper urgent : la société fonctionne en flux tendu...

**Comment by brunoc68** [comment]
Non il n'y a pas de caisse.

**Comment by PatrickMag** [comment]
Est il possible d'avoir les valeurs des dates dteclec1 et dteinv dans Fiches_Parametres et en même temps la date la plus ancienne des histo ventes/achats.

**Comment by brunoc68** [comment]
dteclec1 : 2017-06-30
dteinv : 2017-07-04

ventes : 18-07-2017
achats : 17-07-2017

**Comment by PatrickMag** [comment]
Le stock de départ 0 est bien celui de la fiche article onglet stock ?
Obtient on les mêmes résultats en utilisant l’outil "Interrogation des mouvements de stock" ? En cochant "détail", il y a un petit bug sur les regroupement par date.
Et aussi n'y aurait il pas un inventaire tournant ?

**Comment by brunoc68** [comment]
Oui le 0 est bien celui de la fiche article onglet stock.

Dans interrogation des mouvements de stock je retrouve exactement les mêmes choses, à l'exception d'une "sortie exceptionnelle" de 6 unités qui manquent, c'est à dire 236 en sortie au lieu de 242.

**Comment by PatrickMag** [comment]
Il faut cocher "Inclure les mouvements exceptionnels" 
Il ne reste plus que les inventaires tournant, en effet le programme va d'abord chercher le stock dans la fiche article puis dans l'inventaire tournant et le remplace si il existe.
SELECT inv_qtecomptee,inv_date FROM Fiches_HisInvT WHERE inv_code='codeart';

**Comment by PatrickMag** [comment]
C'est quand même à vérifier avec d'autres bases que les miennes.
