### ISSUE TITLE
Enlever la saisie des règlements v3.68.1 (6157158 branche master)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#83]
Concernant l'option "La saisie des règlements est activée" dans l'onglet Gestion 1 : activée ou pas, la saisie des règlements reste toujours possible.

Plus gênant :

Dans le cas d'une facture avec règlement LCR à 30 jours fin de mois : par défaut on se retrouve avec le règlement total.
Si on ne décoche pas le règlement, au moment où l'on transforme en facture, on se retrouve avec : "Règlement XXX,XX Euros par Lcr au xx.xx.xxx    Facture acquittée", la date étant celle au moment de l'impression.
Si on réouvre le même document et que l'on imprime, on se retrouve avec : "Règlement Lcr au 31.03.2018   Facture acquittée".

Le soucis vient du fait d'avoir la possibilité d'indiquer un règlement, et surtout que cette option arrive par défaut. En effet, en décochant la case règlement, on se retrouve avec : "Règlement Lcr au 31.03.2018" sans la mention "Facture acquittée", ce qui est le comportement correct.

**Comment by damscot** [comment]
ok j'ai fixé le pb de l'option qui ne faisait rien, par contre je comprends pas le pb.
- pour les dates aucun pb chez moi, la date utilisé est celle calculé en fonction de l'echeance client.
- si le règlement est activé il est normal que la facture soit noté acquité non? (LCR passé en banque)
- si le règlement n'est pas activé c'est que le LCR n'est pas encore passé en banque. 

il est vrai que pour le LCR, j'ai du mal à comprendre comment on peut avoir le règlement le jour de l'établissement de la Facture... ce que tu propose c'est que l'option règlement soit désactivé par défaut quand il s'agit de LCR?

@Laurux tu as un avis?

**Comment by Laurux** [comment]
Pour le mode lcr et traite il n'y a aucune écriture de trésorerie. Pour ces modes là l'option règlement est désactivée et les utilisateurs n'ont aucune raison de l'activer puisque le règlement est une traite ou lcr et qu'il interviendra ultérieurement.

**Comment by damscot** [comment]
ok donc il y avait un bug ici, je vais le correctif.
qu'en est il des options virements et prélèvement faut-il également
supprimer l'option saisie de règlement dans ces cas la.
