### ISSUE TITLE
pb maj bases sur multisociété v3.68.1 (1389baf branche v3.68)

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#86]
Lors de la migration 3.67.11 -> 3.68.0 -> 3.68.1, la base n'a pas été correctement mise à jour sur la deuxième société. Après vérification, de même sur la 3e société. En fait, seule la base de la première société est mise à jour, bien que le logiciel indique la nouvelle version dans les paramètres généraux pour les 3 sociétés.

Contournement :
- mettre 3.67 dans les Paramètres / Paramètres généraux / N° version (à la place de 3.68)
- fermer le logiciel et redémarrer

Note : le contournement a fonctionné alors même que la case "Base / Connexion nouvelle base / le poste utilisé ici est celui qui effectue la mlise à jour de la base de données" n'était pas cochée.

**Comment by damscot** [comment]
sais tu quelles tables n'ont pas été mise jour ?
quand tu bascule sur la nouvelle societe tu vas sur la nouvelle base et
chaque base à sa propre table parametres.
Il faudrait par contre voir lors du basculement de société est-ce que l'on
fait bien appel à la mise à jour.

si pb il y a, il se passe forcement entre 3.67 et 3.68 ... la 3.68.1
n'apporte aucun changement de numero de version du coup pas de MAJ.

**Comment by brunoc68** [comment]
Je ne sais pas quelle table n'a pas été mise jour. Je peux toutefois donner une piste : Laurux a crashé au moment où j'ai cherché à créer une nouvelle fiche client avec l'erreur :
Type mismatch : wanted float got null instead, FClient.Button2_Click.1599

**Comment by damscot** [comment]
bruno tu peux m'envoyer la base multisociété en 3.67 pour reproduire ?
merci

2018-03-06 22:29 GMT+01:00 brunoc68 <notifications@github.com>:

**Comment by damscot** [comment]
en accord avec @brunoc68, reproduction du pb non significatif, workaround acceptable décrit ci-dessus
