### ISSUE TITLE
pb modification quantité sur BL pour un client non soumis à TVA

### ISSUE THREAD

**Issue by brunoc68** [Laurux/Laurux#9]
Bonjour,

=== Laurux 3.67.11 ===

Dans 
- la saisie d'un nouveau document (BL)
- pour un client non soumis à la TVA ("Exo" dans la fiche client)
- quand on édite une ligne existante
- et qu'on modifie la quantité
On obtient l'erreur "Veuillez controler votre TVA SVP !"

Impossible de modifier la ligne.
Pour un BL qui fait plusieurs dizaines de lignes, il faut tout recommencer !

Pire : l'utilisatrice a réussi (mais je ne sais pas comment) à tout de même modifier quelque chose. Elle se retrouve avec de la TVA sur le BL (j'imagine qu'elle a édité la fiche client entretemps...).

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:38, brunoc68 a écrit :
> Bonjour,
> 
> Dans
> 
>   * la saisie d'un nouveau document (BL)
>   * pour un client non soumis à la TVA ("Exo" dans la fiche client)
>   * quand on édite une ligne existante
>   * et qu'on modifie la quantité
>     On obtient l'erreur "Veuillez controler votre TVA SVP !"
> 
> Impossible de modifier la ligne.
> 
> Pire : l'utilisatrice a réussi (mais je ne sais pas comment) à tout de 
> même modifier quelque chose. Elle se retrouve avec de la TVA sur le BL 
> (j'imagine qu'elle a édité la fiche client entretemps...).

Bonjour Bruno,

je viens de faire des tests et je n'ai rien d'anormal.
Il me faudrait une sauvegarde SVP pour isoler le problème.
Merci de me donner le numéro du bl concerné ainsi que le code du produit.


-- 
Jacky Tripoteau

**Comment by Laurux** [comment]
Le 12/12/2017 à 10:38, brunoc68 a écrit :
> Bonjour,
> 
> Dans
> 
>   * la saisie d'un nouveau document (BL)
>   * pour un client non soumis à la TVA ("Exo" dans la fiche client)
>   * quand on édite une ligne existante
>   * et qu'on modifie la quantité
>     On obtient l'erreur "Veuillez controler votre TVA SVP !"
> 
> Impossible de modifier la ligne.
> 
> Pire : l'utilisatrice a réussi (mais je ne sais pas comment) à tout de 
> même modifier quelque chose. Elle se retrouve avec de la TVA sur le BL 
> (j'imagine qu'elle a édité la fiche client entretemps...).

Bonjour,

sur le BL concerné le bouton exo est décoché donc le programme calcule 
la TVA. Hors comme ce bl a été saisi en exo la tva n'apparait pas dans 
le bl. D'ou l'erreur.
On ne peut pas transformer en taxable un bl saisit en exo. Il faut le 
supprimer et refaire la saisie.


-- 
Jacky Tripoteau

**Comment by brunoc68** [comment]
Ok j'ai vu le soucis : il y a surement eu un mix avec des articles "Exo"
coché et des articles "Exo" décoché.

Avec "Exo" coché, en rappelant les lignes incriminées et en les revalidant,
la TVA est bien repassée à 0 : pas besoin de supprimer le bon !

Merci Jacky.

**Comment by damscot** [comment]
si la réponse te conviens bruno je propose de clore le ticket
