### ISSUE TITLE
Facture : lignes bon

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#90]
En facturation dans la saisie des lignes bon si on met la zone prix ht à blanc (null) et que l'on clic sur la la Qté le programme plante.

**Comment by Laurux** [comment]
Pourquoi la mettre à blanc puisqu'elle est à 0.00 par défaut ?

**Comment by PatrickMag** [comment]
Il s'agit d'une fausse manip ... ça m'arrive.

**Comment by damscot** [comment]
il faut corriger il est indispensable de corrigé le fautes de saisies, la
gestion des "sanity" de saisies devrait etre géré par une classe basé sur
un oberver de type
lost_focus... en attendant on peut faire un fix rapide pour la 3.68, merci
d'assigner le ticket à l'un d'entre nous.

2018-03-07 18:05 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Le lost_focus existe mais dans ce cas là on passe pas dedans et il est tellement complexe que si l'on bouge quoi que ce soit on plante ailleurs.
Je vais donc faire une modif en dehors du lost_focus ... Après si vous avez une meilleur idée.

**Comment by damscot** [comment]
si tu trouves un correctif c'est l'essentiel... l'implementation importe
peu si ce n'est que quelque lignes.
