### ISSUE TITLE
generation clés

### ISSUE THREAD

**Issue by Laurux** [Laurux/Laurux#91]
Y'a pas moyen d'accelerer la génération des clés lors du passage à la 3.64 ?
 3 heures de moulinage pour 60 000 enregistrements dans Mvt

**Comment by damscot** [comment]
j'ai fait quelques amélioration dans un fix pour la 3.68.2 (utilisation de
la lib openssl a la place de exec "md5sum" mais c'est toujours pas super...
je pense pas que Laurux soit prévu pour autant d'ecriture, aujourd'hui les
récupérations sur les bases utilise des select * from table X... en terme
de perf,
c'est vraiment pas super. il est possible aussi de reduire le nombre de
champ utilisé pour la somme de controle comme proposé par @patrickmag

on pourrait aussi faire une classe en C/C++ et faire un module
correspondant en gambas.... mais c'est pas mal de travail.

2018-03-08 20:33 GMT+01:00 Laurux <notifications@github.com>:

**Comment by damscot** [comment]
pour info tu peux utiliser le "profileur" de gambas pour voir ou est passé
le temps... il est plutot utile cet outil pour optimiser

**Comment by PatrickMag** [comment]
On peut peut être optimiser la lecture des infos de la base mais je doute que ça fasse gagner beaucoup de temps, maintenant avant que nous ont passe du temps dessus il faudrait savoir si il reste beaucoup de grosses bases à mettre a jour ?

**Comment by damscot** [comment]
vu les pb de la 3.68 sur les controles, il faudra refaire le calcul de
toutes les ecritures dans la 3.69 je pense.

**Comment by PatrickMag** [comment]
dans ce cas effectivement
Il faudra alors aussi penser que certaines écritures peuvent se retrouver dans Mvt1

**Comment by PatrickMag** [comment]
https://github.com/PatrickMag/Laurux/commit/d20c2fafbaa946ad791073037c9199075cfe6d65
En 1° approche.

**Comment by PatrickMag** [comment]
7491 enregistrements pour 135 secondes (mesurées avec print time) ce qui donnerait environ 18 minutes pour 60000 enregistrements. Sur mon portable intel core i5.
il faut aussi vérifier les champs que j'ai inclut dans le calcul, c'est important, et à voir si c'est utile de faire un traitement sur mvt1 ? il pourrait y avoir des clôtures d’exercices entre temps.

**Comment by damscot** [comment]
quel est la raison qui ferait changer le controle de sha1 sur mvt1. je
croyais que les ecritures étaient passé en Mvt1 à la cloture et que du coup
elle n'était plus modifiable.

Est-ce que tu poses la question pour la mise à Jour 3.69 pour corriger les
cas ou la cloture d'exercice aurait eu lieu entre les deux?

**Comment by damscot** [comment]
pour les perfs ca me semble acceptable, je vais vérifier les champs... tu
as poussé ta branche ?

**Comment by PatrickMag** [comment]
Oui c'est la question est ce utile de faire un calcul sur Mvt1 si il y a eu une clôture entre la 3.64 et la 3.69 ?
C'est poussé, reste juste a commenter les replace.

**Comment by PatrickMag** [comment]
Mince j'ai poussé sur la 3.68 ...

**Comment by damscot** [comment]
pas grave on met ce dans la 3.68,
il est possible de relancer le calcul dans les outils...techniquement on ne
casse pas la compatibilité de la base.
juste les données. donc ca passe.

2018-03-13 21:22 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by damscot** [comment]
fix des sha1 ok mais performance nulle, difficile de faire mieux depuis gambas
