### ISSUE TITLE
Modification d'écriture

### ISSUE THREAD

**Issue by PatrickMag** [Laurux/Laurux#92]
Problème en modification d'écriture validées ou non, remonté du forum
https://www.laurux.fr/drupal/node/174

**Comment by damscot** [comment]
tu peux traduire de manière simple et reproductible le pb
je suis un peu perdu entre le pb de migration et le pb de modif d'ecriture

2018-03-14 11:17 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Dans la saisie des écritures, modification des écritures validées tu ne rappelle que la première ligne au lieux de l'écriture entière

**Comment by PatrickMag** [comment]
Le bug apparaît que sur les bases nouvellement crées, en faite il manque le champ datem dans le fichier MvtM ce qui déclenche le catch en modification d'écriture.
@damscot  penses tu qu'il soit judicieux de faire rajouter ce champs dans une fenêtre mysql  aux utilisateurs ?
Je pense qu'il y 2 postes sur cette erreur dans le forum.

**Comment by PatrickMag** [comment]
En refaisant jouer les maj ça fonctionne chez moi.

**Comment by damscot** [comment]
oui il serait peut etre interessant de rajouter un programme de requete SQL,
j'ai juste peur que les gens fasse n'importe quoi avec...

le fait de rejouer un MAJ est plutot une bonne idée... il faut revoir la
base par défaut Laurux01.mysql,
j'ai trouvé plein de différence avec une base de donnée ayant eu les MAJ.

2018-03-16 18:49 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by Laurux** [comment]
Avant la base livrée était toujours au format de la version en cours.
maintenant elle reste à une version antérieure (je ne sais plus laquelle)

**Comment by PatrickMag** [comment]
Il y a aussi le fait que de rejouer les maj refait le calcul des clés, pour la certification c'est pas top.

**Comment by damscot** [comment]
je suis en train de fixer le pb de gestion de clés... y'a beaucoup de pb
lié au champ de la table Mvt qui sont changé
sans les passer les ecritures dans MvtM.

Il n'y a pas de champ pour stocker le numéro d'ecriture précédente à
laquelle on est chainé cela penalise aussi les performances.

Le fait de rejouer le calcul, c'est sur il faudra l'enlever une fois que
tous le pb aurons été compris et que l'on puisse mettre en place
des tests automatique de regression.

Pour la base de défault le fichier Laurux01.sql est maintenu a jour à la
dernière version (actuellement 3.68), hélas il y a encore pas mal de pb
entre les tables crée
pendant et à la cloture de l'exercice et celle déjà présente dans la base
par défaut. j'essaierai de rejouer pour la version 3.69 une MAJ plus
ancienne pour
essayé de corriger les pb et continuer de corriger les pb que je vois "à la
mains" dans Laurux01.sql.


Pour répondre plus précisement à ce tiquet on fait quoi ?

Damien.


2018-03-18 21:48 GMT+01:00 PatrickMag <notifications@github.com>:

**Comment by PatrickMag** [comment]
Avant de clore le ticket je pensais attendre un petit peut le retour du 2° utilisateur. Pour les autres points évoqués : 
 *  Un programme pour des requêtes SQL je pense aussi que c'est a prendre avec des "pincettes", ça peut être dangereux
 * Pour rajouter un champ de chaînage d'une écriture précédente ok si c'est une obligation légale sinon je serais tenté de dire tant pis pour les performances.
 * N'y aurais t il pas un moyen de faire le recalcule des clés une seule fois ? Dés que les problèmes seront résolus bien sur.

**Comment by damscot** [comment]
Pour rajouter un champ de chaînage d'une écriture précédente:
l'idee c'est qu'aujourd'hui le chainage se fait avec l'ecriture -1 que
l'ecriture soit provisoire, validée ou autre...
si deux utilisateurs font de la compta en meme temps, il pourrait peut etre
avoir des pb de cles

si on stocke quelque part la liste des chainages c'est plus simple on peut
chainer par compte, avec des trous, etc..
et lors de la verification on va chercher directement la bonne écriture
(plus performant)

l'implementation du chainage n'est pas défini dans le texte de loi, chacun
fait comme il veut.

pour le fait de faire le calcul qu'une seule fois... Hélas si on veut
trouver les bugs... il faut justement que les calculs et controle soient
fait...
sinon on corrigera rien :-)

**Comment by PatrickMag** [comment]
Effectivement je n'avais pas pensé a une utilisation multiposte, ça peut poser des soucis, par contre des trous dans le chaînage je suis pas sur de comprendre. Je vais essayer de prendre un peu plus de temps pour voir le fonctionnement de la compta.
Quand je parlais de recalcule des clés c'est en écriture, en effet ce sera difficile de garantir l'inaltérabilité de la compta si on laisse la possibilité de réécrire les clés.
