### ISSUE TITLE
Manque touche Sortie réglement F7 dans Caisse V3.25.1 (fe6f381 branche V3.25)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#94]
Dans Caisse : après la saisie d'un ticket, après le clic sur F7 (réglement), si le client rajoute un article, il n'y a pas de possibilité de sortie pour revenir au ticket. 
![sortief7](https://user-images.githubusercontent.com/37309435/37469352-5967c14c-2865-11e8-8e57-ecfb575a973f.png)

Le Sortir sans imprimer donne le warning suivant 

![sortief7bis](https://user-images.githubusercontent.com/37309435/37469515-b8925254-2865-11e8-9b9e-55693e013502.png)

**Comment by damscot** [comment]
il faut d'abord supprimer tous les règlements et faire la touche echap pour
revenir à l'edition de ticket.

MAIS LE PLUS IMPORTANT C'EST CA:
1 - On ne pose un ticket sur GITHUB que si le pb est validé apres avoir
posé la question sur le Forum
2 - En cas de pb avéré on pose le ticket dans le bon projet sous Github...
si c'est un bug pour la caisse on le pose sur Laurux-Pos pas sur Laurux.

2018-03-15 15:31 GMT+01:00 patsymill <notifications@github.com>:
