### ISSUE TITLE
Dernier n°client s'incrémente à tort si pas de validation : Table clients V3.68.1(1389baf V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#95]
Le Dernier n° de client s'incrémente à tort lorsque l'on ne valide pas la création du client. (il faut donc le modifier manuellement dans les paramètres généraux). 
Pour les fournisseurs c'est ok.

**Comment by damscot** [comment]
il est impossible de savoir si la personne va oui ou non valider sa
création de client... comme le numéro est attribué au moment de l'appui sur
le button "crée/nouveau"
et qu'il peux y avoir plusieurs poste qui crée des compte clients en meme
temps il est impossible aujourd'hui d'attribuer le numéro au moment de la
validation.
je suis étonné que le pb n'est pas vu également chez les "fournisseurs"

**Comment by Laurux** [comment]
Pour les fournisseurs ce n'est pas le fonctionnement normal. Les fiches fournisseurs doivent fonctionner comme les clients et s'incrémenter dès le clic sur le "bouton créer"

**Comment by damscot** [comment]
je suis d'accord avec Jacky le fonctionnement normal est celui des
clients.. le bug est du coup sur les fournisseurs.


2018-03-17 12:18 GMT+01:00 Laurux <notifications@github.com>:
