### ISSUE TITLE
Lettrage d'un Avoir Fournisseur en saisie trésorerie V3.68.1 (1389baf branche V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#96]
En saisie trésorerie, lorsque l'on saisit un remboursement d'avoir fournisseur - avec activation du lettrage  dans les paramètres comptabilité / divers, le montant s'affiche en négatif au débit au lieu de s'afficher en positif au crédit 

![rembavoir](https://user-images.githubusercontent.com/37309435/37471663-9ae83cdc-286a-11e8-86f3-6ab4922f2651.png)

**Comment by Laurux** [comment]
C'est fonctionnement par défaut de la compta qui prend le parti de diminuer le débit afin d'offrir une vue réelle du compte. Même chose pour les clients.
A modifier manuellement si on souhaite travailler avec le crédit.

**Comment by damscot** [comment]
je suis pas comptable, mais effectivement je croyais qu'en compta on
utilisait que des valeurs positive...

----
http://www.comptanat.fr/general/privee.htm

voir: Les opérations à créditLa comptabilité a ainsi été étendue aux
comptes de fournisseurs et de clients. Les comptes des fournisseurs
enregistrent dans la colonne crédit les augmentations de leurs créances sur
l'entreprise nées leurs ventes non encore payées. Leurs diminutions de
créances résultant des paiements de l'entreprise sont enregistrées dans la
colonne débit. Ce choix d'écrire une diminution de créance positivement
dans la colonne débit plutôt que négativement dans la colonne crédit
s'explique par la difficulté d'effectuer des soustractions avec les moyens
techniques de l'époque où est née la comptabilité.

Damien.

**Comment by Laurux** [comment]
Il faudrait faire valider cela par un comptable mais il me semble que les deux options sont possibles.
Le gros avantages de passer en moins c'est que cela permet, d'un seul coup d'oeil, de connaître le CA d'un compte (débit client ou le crédit fournisseur).

**Comment by damscot** [comment]
ceci n'est donc pas un bug... je clos
