### ISSUE TITLE
Un composant pour plusieurs composés : V3.68.1 (1389baf branche V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#98]
2 composés : article JS206 et JS206-D
1 composant : JS206-S

Lorsque l'on créé les compositions des composés, tout est ok, lorsqu'on les revisionne, c'est la pagaille !

Saisie du JS206
![produit compose js206 apres constitution](https://user-images.githubusercontent.com/37309435/37477124-286de5d2-2877-11e8-964f-fdeb3a24c41e.png)

Saisie du JS206-D
![produit compose js206d apres constitution](https://user-images.githubusercontent.com/37309435/37477281-93b5afc8-2877-11e8-876e-becdf992362b.png)

On contrôle et on va voir dans la table articles 

Visu du JS206
![visu fiche article js206](https://user-images.githubusercontent.com/37309435/37477319-ade8e9c8-2877-11e8-99e1-727080ff5871.png)

Visu du JS206-D
![visu fiche article js206d](https://user-images.githubusercontent.com/37309435/37477337-baf30aa4-2877-11e8-81f4-22e7bd1a3609.png)

Maintenant lorsque l'on retourne dans les constitutions on obtient
![visu js206 dans produit compose](https://user-images.githubusercontent.com/37309435/37477364-d256cd66-2877-11e8-9588-a15705ab0fd0.png)

Et si on retire les lignes en trop, l'affichage avec trop de lignes se déplace sur l'autre composé !

**Comment by Laurux** [comment]
Une sauvegarde SVP pour voir ce qui se passe.

**Comment by damscot** [comment]
peux-tu essayé de creer des articles composés sans le "-" mais en utilisant
"_" a la place...
le comportement bizzard peut venir de l'interprétation des requetes SQL.

2018-03-17 12:08 GMT+01:00 Laurux <notifications@github.com>:

**Comment by patsymill** [comment]
test fait. effectivement cela fonctionne avec un "_" à la place de "-" ou avec aucun tiret ...
et du même coup le topic du 16/03/2018 dans le forum Gestion/facturation : "Stock produit composé" (voir fichier stk_pr_c.tar.gz) n'a pu lieu d'être.
Il reste juste un souci au niveau du choix "stock / entrée des produits composés (topic que je n'ai pas eu le temps de poser)  apparemment pour ces articles composés qui ont le même composant, avant la 1ere entrée en stock Laurux me dit que : "cet article a déja été saisi" (déjà ce n'est pas normal) et quand on fait le le choix '2' remplacer cela additionne au lieu de remplacer. 
je joins à Laurux une sauvegarde. (ne pas faire de modif dessus, car c'est un fichier test; je restore mon fichier réel qui s'arrête à la facture 00082 pour mes clients demain matin) pour le test j'ai créé les articles composant1 et composant_1 et compose1 et 2 et compose_1 et _2. ainsi que les factures 83 et 84.
