### ISSUE TITLE
Tri de la colonne code dans la table des articles V3.68.1 (1389baf branche V3.68)

### ISSUE THREAD

**Issue by patsymill** [Laurux/Laurux#99]
Dans la table des articles, l'ordre alpha croissant ou décroissant de la colonne 'code' n'est pas correct.
C'est ok dans la colonne 'intitulé'.

**Comment by damscot** [comment]
je redis les codes sont des chaines de caractères pas des numéros, l'ordre
est celui défini dans linux pour les chaines de caractères "100" < "99"
alors que 100 > 99

2018-03-15 17:53 GMT+01:00 patsymill <notifications@github.com>:

**Comment by damscot** [comment]
ceci est vrai egalement pour les longueurs de chaines de caratères ex
ZZ est plus petit que AAA, en effet @Laurux (jacky) a fait un padding a gauche avec des espaces
donc ZZ devient dans la requete SQL 
"              ZZ"
AAA devient
"             AAA"
je pense que c'est un choix délibéré de jacky
tu peux répondre a sylvie, merci.

**Comment by damscot** [comment]
ceci est un choix de @Laurux, n'ayant pas eu de reponse je clos le tiquet
